structure(list(url = "https://api-ccte.epa.gov/exposure/seem/demographic/search/by-dtxsid/", 
    status_code = 404L, headers = structure(list(`content-type` = "application/json", 
        `transfer-encoding` = "chunked", connection = "keep-alive", 
        date = "Thu, 18 Sep 2025 17:59:14 GMT", `x-vcap-request-id` = "c1b27b05-5be2-46c1-56e2-c10b9e9c23fe", 
        `x-frame-options` = "DENY", `cache-control` = "max-age=0, must-revalidate, no-transform", 
        `strict-transport-security` = "max-age=31536000", `x-content-type-options` = "nosniff", 
        vary = "Accept-Encoding", `x-cache` = "Error from cloudfront", 
        via = "1.1 7b0365f549e6b2fbadd8ec20314cbda0.cloudfront.net (CloudFront)", 
        `x-amz-cf-pop` = "ATL59-P8", `x-amz-cf-id` = "yNealcyH2etCa3yqmrehuvBMpBm6ba0UYGI_FiuOOo8j0BqInhULgw=="), class = c("insensitive", 
    "list")), all_headers = list(list(status = 404L, version = "HTTP/1.1", 
        headers = structure(list(`content-type` = "application/json", 
            `transfer-encoding` = "chunked", connection = "keep-alive", 
            date = "Thu, 18 Sep 2025 17:59:14 GMT", `x-vcap-request-id` = "c1b27b05-5be2-46c1-56e2-c10b9e9c23fe", 
            `x-frame-options` = "DENY", `cache-control` = "max-age=0, must-revalidate, no-transform", 
            `strict-transport-security` = "max-age=31536000", 
            `x-content-type-options` = "nosniff", vary = "Accept-Encoding", 
            `x-cache` = "Error from cloudfront", via = "1.1 7b0365f549e6b2fbadd8ec20314cbda0.cloudfront.net (CloudFront)", 
            `x-amz-cf-pop` = "ATL59-P8", `x-amz-cf-id` = "yNealcyH2etCa3yqmrehuvBMpBm6ba0UYGI_FiuOOo8j0BqInhULgw=="), class = c("insensitive", 
        "list")))), cookies = structure(list(domain = logical(0), 
        flag = logical(0), path = logical(0), secure = logical(0), 
        expiration = structure(numeric(0), class = c("POSIXct", 
        "POSIXt")), name = logical(0), value = logical(0)), row.names = integer(0), class = "data.frame"), 
    content = charToRaw("{\n  \"timestamp\" : \"2025-09-18T17:59:14.582+00:00\",\n  \"status\" : 404,\n  \"error\" : \"Not Found\",\n  \"path\" : \"/exposure/seem/demographic/search/by-dtxsid/\"\n}"), 
    date = structure(1758218354, class = c("POSIXct", "POSIXt"
    ), tzone = "GMT"), times = c(redirect = 0, namelookup = 3.8e-05, 
    connect = 0, pretransfer = 0.000162, starttransfer = 0.110451, 
    total = 0.11049)), class = "response")
