structure(list(url = "https://api-ccte.epa.gov/chemical/search/start-with/DTXSID7020182", 
    status_code = 401L, headers = structure(list(`content-type` = "application/json;charset=ISO-8859-1", 
        `content-length` = "164", connection = "keep-alive", 
        date = "Mon, 16 Sep 2024 19:14:22 GMT", `strict-transport-security` = "max-age=31536000", 
        `x-content-type-options` = "nosniff", `x-vcap-request-id` = "830584da-ece9-4e41-6e3c-ca68e0bde648", 
        `x-xss-protection` = "1; mode=block", `x-frame-options` = "DENY", 
        `x-cache` = "Error from cloudfront", via = "1.1 263d97c176fc51d1d08116820c013de4.cloudfront.net (CloudFront)", 
        `x-amz-cf-pop` = "IAD89-C1", `x-amz-cf-id` = "YV2RTeQ4dBf5larbDvfiVK--05cWlYM90by2Hk-g4p6AO6PCVfnrlg=="), class = c("insensitive", 
    "list")), all_headers = list(list(status = 401L, version = "HTTP/1.1", 
        headers = structure(list(`content-type` = "application/json;charset=ISO-8859-1", 
            `content-length` = "164", connection = "keep-alive", 
            date = "Mon, 16 Sep 2024 19:14:22 GMT", `strict-transport-security` = "max-age=31536000", 
            `x-content-type-options` = "nosniff", `x-vcap-request-id` = "830584da-ece9-4e41-6e3c-ca68e0bde648", 
            `x-xss-protection` = "1; mode=block", `x-frame-options` = "DENY", 
            `x-cache` = "Error from cloudfront", via = "1.1 263d97c176fc51d1d08116820c013de4.cloudfront.net (CloudFront)", 
            `x-amz-cf-pop` = "IAD89-C1", `x-amz-cf-id` = "YV2RTeQ4dBf5larbDvfiVK--05cWlYM90by2Hk-g4p6AO6PCVfnrlg=="), class = c("insensitive", 
        "list")))), cookies = structure(list(domain = logical(0), 
        flag = logical(0), path = logical(0), secure = logical(0), 
        expiration = structure(numeric(0), class = c("POSIXct", 
        "POSIXt")), name = logical(0), value = logical(0)), row.names = integer(0), class = "data.frame"), 
    content = charToRaw("{\"title\":\"API Header Not Found\",\"detail\":\"Every API call should pass assigned API key through custom http header or query parameter. Request is missing x-api-key.\"}"), 
    date = structure(1726514062, class = c("POSIXct", "POSIXt"
    ), tzone = "GMT"), times = c(redirect = 0, namelookup = 5.2e-05, 
    connect = 0, pretransfer = 0.000157, starttransfer = 0.332792, 
    total = 0.332823)), class = "response")
