structure(list(url = "https://api-ccte.epa.gov/exposure/functional-use/search/by-dtxsid/", 
    status_code = 404L, headers = structure(list(`content-type` = "application/json", 
        `transfer-encoding` = "chunked", connection = "keep-alive", 
        date = "Tue, 16 Jul 2024 19:56:48 GMT", `cache-control` = "max-age=0, must-revalidate, no-transform", 
        `strict-transport-security` = "max-age=31536000", `x-content-type-options` = "nosniff", 
        `x-vcap-request-id` = "d2b8286d-faa4-4562-5647-f6963093234f", 
        `x-xss-protection` = "1; mode=block", `x-frame-options` = "DENY", 
        vary = "Accept-Encoding", `x-cache` = "Error from cloudfront", 
        via = "1.1 c22d4946ef5faea12b8d3942ceb9259a.cloudfront.net (CloudFront)", 
        `x-amz-cf-pop` = "EWR53-P1", `x-amz-cf-id` = "cNNHdgOwcP2_KU0egLKiZsiQ1y5tPhiQ-jmn_b4xDPbfXDRPCVf7Tg==", 
        age = "9"), class = c("insensitive", "list")), all_headers = list(
        list(status = 404L, version = "HTTP/1.1", headers = structure(list(
            `content-type` = "application/json", `transfer-encoding` = "chunked", 
            connection = "keep-alive", date = "Tue, 16 Jul 2024 19:56:48 GMT", 
            `cache-control` = "max-age=0, must-revalidate, no-transform", 
            `strict-transport-security` = "max-age=31536000", 
            `x-content-type-options` = "nosniff", `x-vcap-request-id` = "d2b8286d-faa4-4562-5647-f6963093234f", 
            `x-xss-protection` = "1; mode=block", `x-frame-options` = "DENY", 
            vary = "Accept-Encoding", `x-cache` = "Error from cloudfront", 
            via = "1.1 c22d4946ef5faea12b8d3942ceb9259a.cloudfront.net (CloudFront)", 
            `x-amz-cf-pop` = "EWR53-P1", `x-amz-cf-id` = "cNNHdgOwcP2_KU0egLKiZsiQ1y5tPhiQ-jmn_b4xDPbfXDRPCVf7Tg==", 
            age = "9"), class = c("insensitive", "list")))), 
    cookies = structure(list(domain = logical(0), flag = logical(0), 
        path = logical(0), secure = logical(0), expiration = structure(numeric(0), class = c("POSIXct", 
        "POSIXt")), name = logical(0), value = logical(0)), row.names = integer(0), class = "data.frame"), 
    content = charToRaw("{\n  \"timestamp\" : \"2024-07-16T19:56:48.254+00:00\",\n  \"status\" : 404,\n  \"error\" : \"Not Found\",\n  \"path\" : \"/exposure/functional-use/search/by-dtxsid/\"\n}"), 
    date = structure(1721159808, class = c("POSIXct", "POSIXt"
    ), tzone = "GMT"), times = c(redirect = 0, namelookup = 4.4e-05, 
    connect = 0, pretransfer = 0.00015, starttransfer = 0.017449, 
    total = 0.017477)), class = "response")
