structure(list(url = "https://api-ccte.epa.gov/bioactivity/search/by-dtxsid/DTXSID8031865", 
    status_code = 404L, headers = structure(list(`content-type` = "application/json", 
        `transfer-encoding` = "chunked", connection = "keep-alive", 
        date = "Fri, 22 Mar 2024 12:54:12 GMT", `cache-control` = "no-cache, must-revalidate", 
        `x-vcap-request-id` = "56855e54-5ede-4e7f-6ef7-bbc8c7181c9b", 
        `x-frame-options` = "DENY", `strict-transport-security` = "max-age=31536000", 
        `x-content-type-options` = "nosniff", `x-xss-protection` = "1; mode=block", 
        vary = "Accept-Encoding", `x-cache` = "Error from cloudfront", 
        via = "1.1 43684cbde7a46ef5524f47bc4254eff8.cloudfront.net (CloudFront)", 
        `x-amz-cf-pop` = "ORD51-C4", `x-amz-cf-id` = "nsOJzgIGfXVjRrJmjCPQm2yP8ZaGGPHz1QOkQmPG18sZ4fluqGwyig=="), class = c("insensitive", 
    "list")), all_headers = list(list(status = 404L, version = "HTTP/1.1", 
        headers = structure(list(`content-type` = "application/json", 
            `transfer-encoding` = "chunked", connection = "keep-alive", 
            date = "Fri, 22 Mar 2024 12:54:12 GMT", `cache-control` = "no-cache, must-revalidate", 
            `x-vcap-request-id` = "56855e54-5ede-4e7f-6ef7-bbc8c7181c9b", 
            `x-frame-options` = "DENY", `strict-transport-security` = "max-age=31536000", 
            `x-content-type-options` = "nosniff", `x-xss-protection` = "1; mode=block", 
            vary = "Accept-Encoding", `x-cache` = "Error from cloudfront", 
            via = "1.1 43684cbde7a46ef5524f47bc4254eff8.cloudfront.net (CloudFront)", 
            `x-amz-cf-pop` = "ORD51-C4", `x-amz-cf-id` = "nsOJzgIGfXVjRrJmjCPQm2yP8ZaGGPHz1QOkQmPG18sZ4fluqGwyig=="), class = c("insensitive", 
        "list")))), cookies = structure(list(domain = logical(0), 
        flag = logical(0), path = logical(0), secure = logical(0), 
        expiration = structure(numeric(0), class = c("POSIXct", 
        "POSIXt")), name = logical(0), value = logical(0)), row.names = integer(0), class = "data.frame"), 
    content = charToRaw("{\n  \"timestamp\" : \"2024-03-22T12:54:12.055+00:00\",\n  \"status\" : 404,\n  \"error\" : \"Not Found\",\n  \"path\" : \"/bioactivity/search/by-dtxsid/DTXSID8031865\"\n}"), 
    date = structure(1711112052, class = c("POSIXct", "POSIXt"
    ), tzone = "GMT"), times = c(redirect = 0, namelookup = 4.3e-05, 
    connect = 0, pretransfer = 0.000174, starttransfer = 0.231592, 
    total = 0.231622)), class = "response")
