structure(list(url = "https://api-ccte.epa.gov/bioactivity/search/by-dtxsid/DTXSID8031865", 
    status_code = 401L, headers = structure(list(`content-type` = "application/json;charset=ISO-8859-1", 
        `content-length` = "164", connection = "keep-alive", 
        date = "Thu, 15 Feb 2024 20:52:26 GMT", `x-vcap-request-id` = "2c60e8bc-b9cd-49c0-5d24-20adcdb82f28", 
        `x-frame-options` = "DENY", `strict-transport-security` = "max-age=31536000", 
        `x-content-type-options` = "nosniff", `x-xss-protection` = "1; mode=block", 
        `x-cache` = "Error from cloudfront", via = "1.1 2ba01a121d51ee735a8dde7a86ed73b6.cloudfront.net (CloudFront)", 
        `x-amz-cf-pop` = "EWR53-P1", `x-amz-cf-id` = "07pm9B0djmaE_UoStVFXEaLbTJ19MVWP7V0kNlxcYiIBBU6wCQLqaw=="), class = c("insensitive", 
    "list")), all_headers = list(list(status = 401L, version = "HTTP/1.1", 
        headers = structure(list(`content-type` = "application/json;charset=ISO-8859-1", 
            `content-length` = "164", connection = "keep-alive", 
            date = "Thu, 15 Feb 2024 20:52:26 GMT", `x-vcap-request-id` = "2c60e8bc-b9cd-49c0-5d24-20adcdb82f28", 
            `x-frame-options` = "DENY", `strict-transport-security` = "max-age=31536000", 
            `x-content-type-options` = "nosniff", `x-xss-protection` = "1; mode=block", 
            `x-cache` = "Error from cloudfront", via = "1.1 2ba01a121d51ee735a8dde7a86ed73b6.cloudfront.net (CloudFront)", 
            `x-amz-cf-pop` = "EWR53-P1", `x-amz-cf-id` = "07pm9B0djmaE_UoStVFXEaLbTJ19MVWP7V0kNlxcYiIBBU6wCQLqaw=="), class = c("insensitive", 
        "list")))), cookies = structure(list(domain = logical(0), 
        flag = logical(0), path = logical(0), secure = logical(0), 
        expiration = structure(numeric(0), class = c("POSIXct", 
        "POSIXt")), name = logical(0), value = logical(0)), row.names = integer(0), class = "data.frame"), 
    content = charToRaw("{\"title\":\"API Header Not Found\",\"detail\":\"Every API call should pass assigned API key through custom http header or query parameter. Request is missing x-api-key.\"}"), 
    date = structure(1708030346, class = c("POSIXct", "POSIXt"
    ), tzone = "GMT"), times = c(redirect = 0, namelookup = 5.8e-05, 
    connect = 0, pretransfer = 0.000146, starttransfer = 0.360103, 
    total = 0.360162)), class = "response")
