structure(list(url = "https://api-ccte.epa.gov/bioactivity/search/by-dtxsid/DTXSID8031865", 
    status_code = 404L, headers = structure(list(`content-type` = "application/json", 
        `transfer-encoding` = "chunked", connection = "keep-alive", 
        date = "Wed, 27 Mar 2024 17:15:32 GMT", `cache-control` = "no-cache, must-revalidate", 
        `x-vcap-request-id` = "a27f6edd-ced8-462c-5fd0-26a2e369d954", 
        `x-frame-options` = "DENY", `strict-transport-security` = "max-age=31536000", 
        `x-content-type-options` = "nosniff", `x-xss-protection` = "1; mode=block", 
        vary = "Accept-Encoding", `x-cache` = "Error from cloudfront", 
        via = "1.1 933ff1cca50cf69615381c805530ec5e.cloudfront.net (CloudFront)", 
        `x-amz-cf-pop` = "ATL59-P8", `x-amz-cf-id` = "pts2HgIDgdfbCQcpKh7FrEOsaUqD0lh0BLsmZsdUh5s3dhSmrzuK1Q=="), class = c("insensitive", 
    "list")), all_headers = list(list(status = 404L, version = "HTTP/1.1", 
        headers = structure(list(`content-type` = "application/json", 
            `transfer-encoding` = "chunked", connection = "keep-alive", 
            date = "Wed, 27 Mar 2024 17:15:32 GMT", `cache-control` = "no-cache, must-revalidate", 
            `x-vcap-request-id` = "a27f6edd-ced8-462c-5fd0-26a2e369d954", 
            `x-frame-options` = "DENY", `strict-transport-security` = "max-age=31536000", 
            `x-content-type-options` = "nosniff", `x-xss-protection` = "1; mode=block", 
            vary = "Accept-Encoding", `x-cache` = "Error from cloudfront", 
            via = "1.1 933ff1cca50cf69615381c805530ec5e.cloudfront.net (CloudFront)", 
            `x-amz-cf-pop` = "ATL59-P8", `x-amz-cf-id` = "pts2HgIDgdfbCQcpKh7FrEOsaUqD0lh0BLsmZsdUh5s3dhSmrzuK1Q=="), class = c("insensitive", 
        "list")))), cookies = structure(list(domain = logical(0), 
        flag = logical(0), path = logical(0), secure = logical(0), 
        expiration = structure(numeric(0), class = c("POSIXct", 
        "POSIXt")), name = logical(0), value = logical(0)), row.names = integer(0), class = "data.frame"), 
    content = charToRaw("{\n  \"timestamp\" : \"2024-03-27T17:15:32.980+00:00\",\n  \"status\" : 404,\n  \"error\" : \"Not Found\",\n  \"path\" : \"/bioactivity/search/by-dtxsid/DTXSID8031865\"\n}"), 
    date = structure(1711559732, class = c("POSIXct", "POSIXt"
    ), tzone = "GMT"), times = c(redirect = 0, namelookup = 4.2e-05, 
    connect = 0, pretransfer = 0.000152, starttransfer = 0.347203, 
    total = 0.347259)), class = "response")
