structure(list(url = "https://api-ccte.epa.gov/exposure/product-data/search/by-dtxsid/", 
    status_code = 404L, headers = structure(list(`content-type` = "application/json", 
        `transfer-encoding` = "chunked", connection = "keep-alive", 
        date = "Wed, 24 Jul 2024 11:46:21 GMT", `cache-control` = "max-age=0, must-revalidate, no-transform", 
        `strict-transport-security` = "max-age=31536000", `x-content-type-options` = "nosniff", 
        `x-vcap-request-id` = "75040e34-46f3-4133-64e7-a715491260aa", 
        `x-xss-protection` = "1; mode=block", `x-frame-options` = "DENY", 
        vary = "Accept-Encoding", `x-cache` = "Error from cloudfront", 
        via = "1.1 3aed7f1651246872b9b4d9854870e1ca.cloudfront.net (CloudFront)", 
        `x-amz-cf-pop` = "DFW57-P7", `x-amz-cf-id` = "-6Xlbk5H6LiWdrFpHNqLFuwyBTZxbXGMkqhGzLA8lr434AqmbQ3MRg=="), class = c("insensitive", 
    "list")), all_headers = list(list(status = 404L, version = "HTTP/1.1", 
        headers = structure(list(`content-type` = "application/json", 
            `transfer-encoding` = "chunked", connection = "keep-alive", 
            date = "Wed, 24 Jul 2024 11:46:21 GMT", `cache-control` = "max-age=0, must-revalidate, no-transform", 
            `strict-transport-security` = "max-age=31536000", 
            `x-content-type-options` = "nosniff", `x-vcap-request-id` = "75040e34-46f3-4133-64e7-a715491260aa", 
            `x-xss-protection` = "1; mode=block", `x-frame-options` = "DENY", 
            vary = "Accept-Encoding", `x-cache` = "Error from cloudfront", 
            via = "1.1 3aed7f1651246872b9b4d9854870e1ca.cloudfront.net (CloudFront)", 
            `x-amz-cf-pop` = "DFW57-P7", `x-amz-cf-id` = "-6Xlbk5H6LiWdrFpHNqLFuwyBTZxbXGMkqhGzLA8lr434AqmbQ3MRg=="), class = c("insensitive", 
        "list")))), cookies = structure(list(domain = logical(0), 
        flag = logical(0), path = logical(0), secure = logical(0), 
        expiration = structure(numeric(0), class = c("POSIXct", 
        "POSIXt")), name = logical(0), value = logical(0)), row.names = integer(0), class = "data.frame"), 
    content = charToRaw("{\n  \"timestamp\" : \"2024-07-24T11:46:21.362+00:00\",\n  \"status\" : 404,\n  \"error\" : \"Not Found\",\n  \"path\" : \"/exposure/product-data/search/by-dtxsid/\"\n}"), 
    date = structure(1721821581, class = c("POSIXct", "POSIXt"
    ), tzone = "GMT"), times = c(redirect = 0, namelookup = 4.5e-05, 
    connect = 0, pretransfer = 0.000174, starttransfer = 0.116843, 
    total = 0.116872)), class = "response")
