structure(list(url = "https://api-ccte.epa.gov/bioactivity/search/by-dtxsid/DTXSID8031865", 
    status_code = 404L, headers = structure(list(`content-type` = "application/json", 
        `transfer-encoding` = "chunked", connection = "keep-alive", 
        date = "Fri, 22 Mar 2024 12:58:09 GMT", `cache-control` = "no-cache, must-revalidate", 
        `x-vcap-request-id` = "2de3be2c-ab04-464a-61a7-6cffc7f2ca68", 
        `x-frame-options` = "DENY", `strict-transport-security` = "max-age=31536000", 
        `x-content-type-options` = "nosniff", `x-xss-protection` = "1; mode=block", 
        vary = "Accept-Encoding", `x-cache` = "Error from cloudfront", 
        via = "1.1 9f67823435998c04ac9be5fb7449a3c4.cloudfront.net (CloudFront)", 
        `x-amz-cf-pop` = "ATL59-P8", `x-amz-cf-id` = "5gpLGQKI2-aib5ejpfUMoARrbKzN1m9jZSeLeROKKSnv_g0ix7xyTA=="), class = c("insensitive", 
    "list")), all_headers = list(list(status = 404L, version = "HTTP/1.1", 
        headers = structure(list(`content-type` = "application/json", 
            `transfer-encoding` = "chunked", connection = "keep-alive", 
            date = "Fri, 22 Mar 2024 12:58:09 GMT", `cache-control` = "no-cache, must-revalidate", 
            `x-vcap-request-id` = "2de3be2c-ab04-464a-61a7-6cffc7f2ca68", 
            `x-frame-options` = "DENY", `strict-transport-security` = "max-age=31536000", 
            `x-content-type-options` = "nosniff", `x-xss-protection` = "1; mode=block", 
            vary = "Accept-Encoding", `x-cache` = "Error from cloudfront", 
            via = "1.1 9f67823435998c04ac9be5fb7449a3c4.cloudfront.net (CloudFront)", 
            `x-amz-cf-pop` = "ATL59-P8", `x-amz-cf-id` = "5gpLGQKI2-aib5ejpfUMoARrbKzN1m9jZSeLeROKKSnv_g0ix7xyTA=="), class = c("insensitive", 
        "list")))), cookies = structure(list(domain = logical(0), 
        flag = logical(0), path = logical(0), secure = logical(0), 
        expiration = structure(numeric(0), class = c("POSIXct", 
        "POSIXt")), name = logical(0), value = logical(0)), row.names = integer(0), class = "data.frame"), 
    content = charToRaw("{\n  \"timestamp\" : \"2024-03-22T12:58:09.868+00:00\",\n  \"status\" : 404,\n  \"error\" : \"Not Found\",\n  \"path\" : \"/bioactivity/search/by-dtxsid/DTXSID8031865\"\n}"), 
    date = structure(1711112289, class = c("POSIXct", "POSIXt"
    ), tzone = "GMT"), times = c(redirect = 0, namelookup = 5.9e-05, 
    connect = 0, pretransfer = 0.000194, starttransfer = 0.29281, 
    total = 0.292839)), class = "response")
