structure(list(url = "https://api-ccte.epa.gov/hazard/human/search/by-dtxsid/", 
    status_code = 401L, headers = structure(list(`content-type` = "application/json;charset=ISO-8859-1", 
        `content-length` = "164", connection = "keep-alive", 
        date = "Thu, 15 Feb 2024 20:57:07 GMT", `x-vcap-request-id` = "a85da419-b1d4-40ec-4087-b67d581b4dc0", 
        `x-frame-options` = "DENY", `strict-transport-security` = "max-age=31536000", 
        `x-content-type-options` = "nosniff", `x-xss-protection` = "1; mode=block", 
        `x-cache` = "Error from cloudfront", via = "1.1 2ba01a121d51ee735a8dde7a86ed73b6.cloudfront.net (CloudFront)", 
        `x-amz-cf-pop` = "EWR53-P1", `x-amz-cf-id` = "hAL3Fd0x02mxmq157YKW7BhvGe6bIG8EMjLl7SbsAVW5aP6Nsr9Hqg=="), class = c("insensitive", 
    "list")), all_headers = list(list(status = 401L, version = "HTTP/1.1", 
        headers = structure(list(`content-type` = "application/json;charset=ISO-8859-1", 
            `content-length` = "164", connection = "keep-alive", 
            date = "Thu, 15 Feb 2024 20:57:07 GMT", `x-vcap-request-id` = "a85da419-b1d4-40ec-4087-b67d581b4dc0", 
            `x-frame-options` = "DENY", `strict-transport-security` = "max-age=31536000", 
            `x-content-type-options` = "nosniff", `x-xss-protection` = "1; mode=block", 
            `x-cache` = "Error from cloudfront", via = "1.1 2ba01a121d51ee735a8dde7a86ed73b6.cloudfront.net (CloudFront)", 
            `x-amz-cf-pop` = "EWR53-P1", `x-amz-cf-id` = "hAL3Fd0x02mxmq157YKW7BhvGe6bIG8EMjLl7SbsAVW5aP6Nsr9Hqg=="), class = c("insensitive", 
        "list")))), cookies = structure(list(domain = logical(0), 
        flag = logical(0), path = logical(0), secure = logical(0), 
        expiration = structure(numeric(0), class = c("POSIXct", 
        "POSIXt")), name = logical(0), value = logical(0)), row.names = integer(0), class = "data.frame"), 
    content = charToRaw("{\"title\":\"API Header Not Found\",\"detail\":\"Every API call should pass assigned API key through custom http header or query parameter. Request is missing x-api-key.\"}"), 
    date = structure(1708030627, class = c("POSIXct", "POSIXt"
    ), tzone = "GMT"), times = c(redirect = 0, namelookup = 3.1e-05, 
    connect = 0, pretransfer = 1e-04, starttransfer = 0.213723, 
    total = 0.213778)), class = "response")
