structure(list(url = "https://api-ccte.epa.gov/exposure/seem/demographic/search/by-dtxsid/", 
    status_code = 404L, headers = structure(list(`content-type` = "application/json", 
        `transfer-encoding` = "chunked", connection = "keep-alive", 
        date = "Thu, 18 Sep 2025 19:25:55 GMT", `x-vcap-request-id` = "573dc300-f7a4-4371-50b2-fbb150cd23de", 
        `x-frame-options` = "DENY", `cache-control` = "max-age=0, must-revalidate, no-transform", 
        `strict-transport-security` = "max-age=31536000", `x-content-type-options` = "nosniff", 
        vary = "Accept-Encoding", `x-cache` = "Error from cloudfront", 
        via = "1.1 87fd86cc57c26e58e2dfe4914bc636f6.cloudfront.net (CloudFront)", 
        `x-amz-cf-pop` = "ATL59-P8", `x-amz-cf-id` = "6L1MsUMoZ0FDYn2NoytYqg9t6G5EQ_2K6wDpf0cp4ivkqptW-wF6lw=="), class = c("insensitive", 
    "list")), all_headers = list(list(status = 404L, version = "HTTP/1.1", 
        headers = structure(list(`content-type` = "application/json", 
            `transfer-encoding` = "chunked", connection = "keep-alive", 
            date = "Thu, 18 Sep 2025 19:25:55 GMT", `x-vcap-request-id` = "573dc300-f7a4-4371-50b2-fbb150cd23de", 
            `x-frame-options` = "DENY", `cache-control` = "max-age=0, must-revalidate, no-transform", 
            `strict-transport-security` = "max-age=31536000", 
            `x-content-type-options` = "nosniff", vary = "Accept-Encoding", 
            `x-cache` = "Error from cloudfront", via = "1.1 87fd86cc57c26e58e2dfe4914bc636f6.cloudfront.net (CloudFront)", 
            `x-amz-cf-pop` = "ATL59-P8", `x-amz-cf-id` = "6L1MsUMoZ0FDYn2NoytYqg9t6G5EQ_2K6wDpf0cp4ivkqptW-wF6lw=="), class = c("insensitive", 
        "list")))), cookies = structure(list(domain = logical(0), 
        flag = logical(0), path = logical(0), secure = logical(0), 
        expiration = structure(numeric(0), class = c("POSIXct", 
        "POSIXt")), name = logical(0), value = logical(0)), row.names = integer(0), class = "data.frame"), 
    content = charToRaw("{\n  \"timestamp\" : \"2025-09-18T19:25:55.084+00:00\",\n  \"status\" : 404,\n  \"error\" : \"Not Found\",\n  \"path\" : \"/exposure/seem/demographic/search/by-dtxsid/\"\n}"), 
    date = structure(1758223555, class = c("POSIXct", "POSIXt"
    ), tzone = "GMT"), times = c(redirect = 0, namelookup = 4.8e-05, 
    connect = 0, pretransfer = 0.000167, starttransfer = 0.112781, 
    total = 0.112818)), class = "response")
