structure(list(url = "https://comptox.epa.gov/ctx-api/exposure/ccd/puc/search/by-dtxsid/", 
    status_code = 404L, headers = structure(list(date = "Mon, 06 Oct 2025 16:55:05 GMT", 
        server = "Apache", `strict-transport-security` = "max-age=63072000; includeSubDomains; preload“", 
        vary = "Origin,Access-Control-Request-Method,Access-Control-Request-Headers", 
        `cache-control` = "max-age=0, must-revalidate, no-transform", 
        `content-type` = "application/json", `transfer-encoding` = "chunked"), class = c("insensitive", 
    "list")), all_headers = list(list(status = 404L, version = "HTTP/1.1", 
        headers = structure(list(date = "Mon, 06 Oct 2025 16:55:05 GMT", 
            server = "Apache", `strict-transport-security` = "max-age=63072000; includeSubDomains; preload“", 
            vary = "Origin,Access-Control-Request-Method,Access-Control-Request-Headers", 
            `cache-control` = "max-age=0, must-revalidate, no-transform", 
            `content-type` = "application/json", `transfer-encoding` = "chunked"), class = c("insensitive", 
        "list")))), cookies = structure(list(domain = logical(0), 
        flag = logical(0), path = logical(0), secure = logical(0), 
        expiration = structure(numeric(0), class = c("POSIXct", 
        "POSIXt")), name = logical(0), value = logical(0)), row.names = integer(0), class = "data.frame"), 
    content = charToRaw("{\n  \"timestamp\" : \"2025-10-06T16:55:05.922+00:00\",\n  \"status\" : 404,\n  \"error\" : \"Not Found\",\n  \"path\" : \"/exposure/ccd/puc/search/by-dtxsid/\"\n}"), 
    date = structure(1759769705, class = c("POSIXct", "POSIXt"
    ), tzone = "GMT"), times = c(redirect = 0, namelookup = 4.3e-05, 
    connect = 0, pretransfer = 0.00018, starttransfer = 0.035627, 
    total = 0.035655)), class = "response")
