structure(list(url = "https://comptox.epa.gov/ctx-api/bioactivity/analyticalqc/search/by-dtxsid/", 
    status_code = 404L, headers = structure(list(date = "Thu, 07 May 2026 19:52:38 GMT", 
        server = "Apache", `strict-transport-security` = "max-age=63072000; includeSubDomains; preload“", 
        `access-control-allow-origin` = "*", vary = "Origin,Access-Control-Request-Method,Access-Control-Request-Headers", 
        `cache-control` = "no-cache, must-revalidate", `content-type` = "application/json", 
        `transfer-encoding` = "chunked"), class = c("insensitive", 
    "list")), all_headers = list(list(status = 404L, version = "HTTP/1.1", 
        headers = structure(list(date = "Thu, 07 May 2026 19:52:38 GMT", 
            server = "Apache", `strict-transport-security` = "max-age=63072000; includeSubDomains; preload“", 
            `access-control-allow-origin` = "*", vary = "Origin,Access-Control-Request-Method,Access-Control-Request-Headers", 
            `cache-control` = "no-cache, must-revalidate", `content-type` = "application/json", 
            `transfer-encoding` = "chunked"), class = c("insensitive", 
        "list")))), cookies = structure(list(domain = logical(0), 
        flag = logical(0), path = logical(0), secure = logical(0), 
        expiration = structure(numeric(0), class = c("POSIXct", 
        "POSIXt")), name = logical(0), value = logical(0)), row.names = integer(0), class = "data.frame"), 
    content = charToRaw("{\n  \"timestamp\" : \"2026-05-07T19:52:38.229+00:00\",\n  \"status\" : 404,\n  \"error\" : \"Not Found\",\n  \"path\" : \"/bioactivity/analyticalqc/search/by-dtxsid/\"\n}"), 
    date = structure(1778183558, class = c("POSIXct", "POSIXt"
    ), tzone = "GMT"), times = c(redirect = 0, namelookup = 3.9e-05, 
    connect = 0, pretransfer = 0.000182, starttransfer = 0.03923, 
    total = 0.039282)), class = "response")
