test_that("catch missing APIs", {
  expect_error(get_chemical_details_batch(), 'Please input a character string containing a valid API key!')
  expect_error(get_chemical_details_batch(API_key = 1), 'Please input a character string containing a valid API key!')
  expect_error(get_chem_info_batch(), 'Please input a character string containing a valid API key!')
  expect_error(get_chem_info_batch(API_key = 1), 'Please input a character string containing a valid API key!')
  expect_error(get_fate_by_dtxsid_batch(), 'Please input a character string containing a valid API key!')
  expect_error(get_fate_by_dtxsid_batch(API_key = 1), 'Please input a character string containing a valid API key!')
  expect_error(chemical_starts_with_batch(), 'Please input a character string containing a valid API key!')
  expect_error(chemical_starts_with_batch(API_key = 1), 'Please input a character string containing a valid API key!')
  expect_error(chemical_equal_batch(), 'Please input a character string containing a valid API key!')
  expect_error(chemical_equal_batch(API_key = 1), 'Please input a character string containing a valid API key!')
  expect_error(chemical_contains_batch(), 'Please input a character string containing a valid API key!')
  expect_error(chemical_contains_batch(API_key = 1), 'Please input a character string containing a valid API key!')
  expect_error(get_msready_by_mass_batch(), 'Please input a character string containing a valid API key!')
  expect_error(get_msready_by_mass_batch(API_key = 1), 'Please input a character string containing a valid API key!')
  expect_error(get_msready_by_formula_batch(), 'Please input a character string containing a valid API key!')
  expect_error(get_msready_by_formula_batch(API_key = 1), 'Please input a character string containing a valid API key!')
  expect_error(get_msready_by_dtxcid_batch(), 'Please input a character string containing a valid API key!')
  expect_error(get_msready_by_dtxcid_batch(API_key = 1), 'Please input a character string containing a valid API key!')
  expect_error(get_chemical_lists_by_type_batch(), 'Please input a character string containing a valid API key!')
  expect_error(get_chemical_lists_by_type_batch(API_key = 1), 'Please input a character string containing a valid API key!')
  expect_error(get_public_chemical_list_by_name_batch(), 'Please input a character string containing a valid API key!')
  expect_error(get_public_chemical_list_by_name_batch(API_key = 1), 'Please input a character string containing a valid API key!')
  expect_error(get_lists_containing_chemical_batch(), 'Please input a character string containing a valid API key!')
  expect_error(get_lists_containing_chemical_batch(API_key = 1), 'Please input a character string containing a valid API key!')
  expect_error(get_chemicals_in_list_batch(), 'Please input a character string containing a valid API key!')
  expect_error(get_chemicals_in_list_batch(API_key = 1), 'Please input a character string containing a valid API key!')
  expect_error(get_chemical_mrv_batch(), 'Please input a character string containing a valid API key!')
  expect_error(get_chemical_mrv_batch(API_key = 1), 'Please input a character string containing a valid API key!')
  expect_error(get_chemical_mol_batch(), 'Please input a character string containing a valid API key!')
  expect_error(get_chemical_mol_batch(API_key = 1), 'Please input a character string containing a valid API key!')
  expect_error(get_chemical_image_batch(), 'Please input a character string containing a valid API key!')
  expect_error(get_chemical_image_batch(API_key = 1), 'Please input a character string containing a valid API key!')
  expect_error(get_chemical_synonym_batch(), 'Please input a character string containing a valid API key!')
  expect_error(get_chemical_synonym_batch(API_key = 1), 'Please input a character string containing a valid API key!')
})
