test_that("catch missing API", {
  expect_error(get_chemical_details(DTXSID = 'DTXSID7020182'), 'Please input an API_key')
  expect_error(get_chemical_by_property_range(), 'Please input an API_key')
  expect_error(get_chem_info(DTXSID = 'DTXSID7020182'), 'Please input an API_key')
  expect_error(get_fate_by_dtxsid(DTXSID = 'DTXSID7020182'), 'Please input an API_key')
  expect_error(chemical_starts_with(word = 'DTXSID7020182'), 'Please input an API_key')
  expect_error(chemical_equal(word = 'DTXSID7020182'), 'Please input an API_key')
  expect_error(chemical_contains(word = 'DTXSID7020182'), 'Please input an API_key')
  expect_error(get_msready_by_mass(start = 1, end = 2), 'Please input an API_key')
  expect_error(get_msready_by_formula(formula = 'C2H6'), 'Please input an API_key')
  expect_error(get_msready_by_formula(formula = 'C2H6'), 'Please input an API_key')
  expect_error(get_msready_by_dtxcid(DTXCID = 'DTXCID705545'), 'Please input an API_key')
  expect_error(get_chemical_lists_by_type(type = 'other'), 'Please input an API_key')
  expect_error(get_public_chemical_list_by_name(list_name = 'Biosolids2021'), 'Please input an API_key')
  expect_error(get_lists_containing_chemical(DTXSID = 'DTXSID7020182'), 'Please input an API_key')
  expect_error(get_chemicals_in_list(list_name = 'Biosolids2021'), 'Please input an API_key')
  expect_error(get_all_public_chemical_lists(), 'Please input an API_key')
  expect_error(get_chemical_mrv(DTXSID = 'DTXSID7020182'), 'Please input an API_key')
  expect_error(get_chemical_mol(DTXSID = 'DTXSID7020182'), 'Please input an API_key')
  expect_error(get_chemical_image(DTXSID = 'DTXSID7020182'), 'Please input an API_key')
  expect_error(get_chemical_synonym(DTXSID = 'DTXSID7020182'), 'Please input an API_key')
})

test_that("catch missing DTXSID/DTXCID", {
  expect_error(get_chemical_details(), 'Please input a DTXSID or DTXCID!')
  expect_error(get_chem_info(), 'Please input a DTXSID!')
  expect_error(get_fate_by_dtxsid(), 'Please input a DTXSID!')
  expect_error(get_msready_by_dtxcid(), 'Please input a non-null value for DTXCID!')
  expect_error(get_msready_by_dtxcid(DTXCID = 1), 'Please input a character string for the DTXCID parameter!')
  expect_error(get_lists_containing_chemical(), 'Please input a non-null value for DTXSID!')
  expect_error(get_chemical_mrv(), 'Please input a DTXSID or DTXCID!')
  expect_error(get_chemical_mol(), 'Please input a DTXSID or DTXCID!')
  expect_error(get_chemical_image(), 'Please input a DTXSID or DTXCID!')
  expect_error(get_chemical_synonym(), 'Please input a DTXSID!')
})

test_that('Catch both DTXSID and DTXCID', {
  expect_error(get_chemical_details(DTXSID = 'DTXSID7020182', DTXCID = 'DTXCID30182'), 'Please input either a DTXSID or DTXCID, but not both!')
  expect_error(get_chemical_mrv(DTXSID = 'DTXSID7020182', DTXCID = 'DTXCID30182'), 'Please input either a DTXSID or DTXCID, but not both!')
  expect_error(get_chemical_mol(DTXSID = 'DTXSID7020182', DTXCID = 'DTXCID30182'), 'Please input either a DTXSID or DTXCID, but not both!')
  expect_error(get_chemical_image(DTXSID = 'DTXSID7020182', DTXCID = 'DTXCID30182'), 'Please input either a DTXSID or DTXCID, but not both!')

})

test_that('Numeric range input errors and warnings', {
  expect_error(get_chemical_by_property_range(API_key = 'test_key'), 'Please input a numeric value for both start and end!')
  expect_error(get_chemical_by_property_range(start = 4, API_key = 'test_key'), 'Please input a numeric value for both start and end!')
  expect_error(get_chemical_by_property_range(end = 4, API_key = 'test_key'), 'Please input a numeric value for both start and end!')
  expect_error(get_chemical_by_property_range(start = 4, end = 'k', API_key = 'test_key'), 'Please input a numeric value for both start and end!')
  expect_error(get_chemical_by_property_range(start = TRUE, end = 4, API_key = 'test_key'), 'Please input a numeric value for both start and end!')
  expect_error(get_chemical_by_property_range(start = 3, end = 4, API_key = Sys.getenv('CCTE_API_KEY')), 'Please input a value for property!')
  expect_error(get_msready_by_mass(API_key = 'test_key'), 'Please input a numeric value for both start and end!')
  expect_error(get_msready_by_mass(start = 4, API_key = 'test_key'), 'Please input a numeric value for both start and end!')
  expect_error(get_msready_by_mass(end = 4, API_key = 'test_key'), 'Please input a numeric value for both start and end!')
  expect_error(get_msready_by_mass(start = 4, end = 'k', API_key = 'test_key'), 'Please input a numeric value for both start and end!')
  expect_error(get_msready_by_mass(start = TRUE, end = 4, API_key = 'test_key'), 'Please input a numeric value for both start and end!')
  expect_error(get_msready_by_mass(start = -1, end = 4, API_key = 'test_key'), 'Both start and end must be non-negative!')
  expect_error(get_msready_by_mass(start = 4, end = -1, API_key = 'test_key'), 'Both start and end must be non-negative!')
  expect_warning(get_msready_by_mass(start = 4, end = 1, API_key = 'test_key'), 'Swapping values for start and end!')
  #expect_warning(get_chemical_by_property_range(start = 4, end = 3, property = 'density', API_key = Sys.getenv('CCTE_API_KEY')), 'Swapping values for start and end!')

})

test_that('projection/type errors/warnings', {
  expect_warning(get_chemical_details(DTXSID = 'DTXSID7020182', Projection = 't', API_key = 'test_key'), 'Setting `Projection` to `chemicaldetailstandard`')
  expect_warning(get_chemical_details(DTXSID = 'DTXSID7020182', Projection =  2, API_key = 'test_key'), 'Setting `Projection` to `chemicaldetailstandard`')
  expect_warning(get_chem_info(DTXSID = 'DTXSID', type = c('', 'predicted'), API_key = 'test_key'), 'Setting type to ""!')
  expect_error(get_chem_info(DTXSID = 'DTXSID', type = 'l', API_key = 'test_key'), 'Please input a correct choice for type!')
  expect_error(get_chemical_lists_by_type(), 'Please input a value for parameter type')
  expect_error(get_chemical_lists_by_type(type = 1), 'Please input a value for parameter type')
  expect_warning(get_chemical_lists_by_type(type = 'federal', Projection = 1, API_key = Sys.getenv('CCTE_API_KEY')), 'Setting `Projection` to empty string!')
  expect_warning(get_chemical_lists_by_type(type = 'federal', Projection = '1', API_key = Sys.getenv('CCTE_API_KEY')), 'Setting `Projection` to empty string!')
  expect_warning(get_chemical_lists_by_type(type = 'federal', Projection = c('', 'chemicallistall'), API_key = Sys.getenv('CCTE_API_KEY')), 'Setting `Projection` to empty string!')
  expect_warning(get_public_chemical_list_by_name(list_name = 'federal', Projection = 1, API_key = Sys.getenv('CCTE_API_KEY')), 'Setting `Projection` to empty string!')
  expect_warning(get_public_chemical_list_by_name(list_name = 'federal', Projection = '1', API_key = Sys.getenv('CCTE_API_KEY')), 'Setting `Projection` to empty string!')
  expect_warning(get_public_chemical_list_by_name(list_name = 'federal', Projection = c('', 'chemicallistall'), API_key = Sys.getenv('CCTE_API_KEY')), 'Setting `Projection` to empty string!')
  expect_warning(get_all_public_chemical_lists(Projection = 1, API_key = Sys.getenv('CCTE_API_KEY')), 'Setting `Projection` to empty string!')
  expect_warning(get_all_public_chemical_lists(Projection = '1', API_key = Sys.getenv('CCTE_API_KEY')), 'Setting `Projection` to empty string!')
  expect_warning(get_all_public_chemical_lists(Projection = c('', 'chemicallistall'), API_key = Sys.getenv('CCTE_API_KEY')), 'Setting `Projection` to empty string!')
})

test_that('Word search errors', {
  expect_error(chemical_starts_with(), 'Please input a character value for word!')
  expect_error(chemical_starts_with(word = 1), 'Please input a character value for word!')
  expect_error(chemical_equal(), 'Please input a character value for word!')
  expect_error(chemical_equal(word = 1), 'Please input a character value for word!')
  expect_error(chemical_contains(), 'Please input a character value for word!')
  expect_error(chemical_contains(word = 1), 'Please input a character value for word!')
  expect_error(get_msready_by_formula(), 'Please input a non-null value for formula!')
  expect_error(get_msready_by_formula(formula = 1), 'Please input a character string for the formula parameter!')
  expect_error(get_public_chemical_list_by_name(), 'Please input list_name!')
  expect_error(get_lists_containing_chemical(), 'Please input a non-null value for DTXSID!')
  expect_error(get_chemicals_in_list(), 'Please input a character value for list_name!')
  expect_error(get_chemicals_in_list(list_name = 1), 'Please input a character value for list_name!')
})

test_that('Return data type', {
  expect_type(get_chemical_details(DTXSID = 'DTXSID7020182', API_key = Sys.getenv('CCTE_API_KEY')), 'list')
  expect_type(get_chemical_details(DTXCID = 'DTXCID30182', API_key = Sys.getenv('CCTE_API_KEY')), 'list')
  expect_type(get_chemical_details(DTXSID = '', API_key = Sys.getenv('CCTE_API_KEY')), 'NULL')
  #expect_type(get_chemical_details(DTXSID = 'DTXSID7020182', API_key = ''), 'NULL')
  #expect_type(get_chemical_by_property_range(start = 99.8, end = 100.2, property = 'boiling point', API_key = Sys.getenv('CCTE_API_KEY')), 'list')
  #expect_type(get_chemical_by_property_range(start = 99.8, end = 100.2, property = 'nonsense', API_key = Sys.getenv('CCTE_API_KEY')), 'NULL')
  expect_type(get_chem_info(DTXSID = 'DTXSID7020182', API_key = Sys.getenv('CCTE_API_KEY')), 'list')
  expect_type(get_chem_info(DTXSID = 'DTXSID7020182', type = 'predicted', API_key = Sys.getenv('CCTE_API_KEY')), 'list')
  expect_type(get_chem_info(DTXSID = '', API_key = Sys.getenv('CCTE_API_KEY')), 'NULL')
  #expect_type(get_chem_info(DTXSID = 'DTXSID7020182', API_key = ''), 'NULL')
  expect_type(get_fate_by_dtxsid(DTXSID = 'DTXSID7020182', API_key = Sys.getenv('CCTE_API_KEY')), 'list')
  expect_type(get_fate_by_dtxsid(DTXSID = '', API_key = Sys.getenv('CCTE_API_KEY')), 'NULL')
  #expect_type(get_fate_by_dtxsid(DTXSID = 'DTXSID7020182', API_key = ''), 'NULL')
  expect_type(chemical_starts_with(word = 'DTXSID7020182', API_key = Sys.getenv('CCTE_API_KEY')), 'list')
  expect_type(chemical_starts_with(word = '', API_key = Sys.getenv('CCTE_API_KEY')), 'NULL')
  #expect_type(chemical_starts_with(word = 'DTXSID7020182', API_key = ''), 'NULL')
  expect_type(chemical_equal(word = 'Bisphenol A', API_key = Sys.getenv('CCTE_API_KEY')), 'list')
  expect_type(chemical_equal(word = 'gvfds', API_key = Sys.getenv('CCTE_API_KEY')), 'NULL')
  #expect_type(chemical_equal(word = 'Bisphenol A', API_key = ''), 'NULL')
  expect_type(chemical_contains(word = 'Bisphenol A', API_key = Sys.getenv('CCTE_API_KEY')), 'list')
  expect_type(chemical_contains(word = 'gvfdsr7', API_key = Sys.getenv('CCTE_API_KEY')), 'NULL')
  #expect_type(chemical_contains(word = 'Bisphenol A', API_key = ''), 'NULL')
  expect_type(get_msready_by_mass(start = 16.0313, end = 16.0314, API_key = Sys.getenv('CCTE_API_KEY')), 'character')
  expect_type(get_msready_by_mass(start = 16.0314, end = 16.0314, API_key = Sys.getenv('CCTE_API_KEY')), 'list')
  #expect_type(get_msready_by_mass(start = 16.0313, end = 16.0314, API_key =''), 'NULL')
  expect_type(get_msready_by_formula(formula = 'CH4', API_key = Sys.getenv('CCTE_API_KEY')), 'character')
  expect_type(get_msready_by_formula(formula = '8x', API_key = Sys.getenv('CCTE_API_KEY')), 'list')
  expect_type(get_msready_by_formula(formula = '', API_key = Sys.getenv('CCTE_API_KEY')), 'NULL')
  #expect_type(get_msready_by_formula(formula = 'CH4', API_key = ''), 'NULL')
  expect_type(get_msready_by_dtxcid(DTXCID = 'DTXCID30182', API_key = Sys.getenv('CCTE_API_KEY')), 'character')
  expect_type(get_msready_by_dtxcid(DTXCID = '', API_key = Sys.getenv('CCTE_API_KEY')), 'NULL')
  #expect_type(get_msready_by_dtxcid(DTXCID = 'DTXCID30182', API_key = ''), 'NULL')
  expect_type(get_chemical_lists_by_type(type = 'federal', API_key = Sys.getenv('CCTE_API_KEY')), 'list')
  expect_type(get_chemical_lists_by_type(type = '', API_key = Sys.getenv('CCTE_API_KEY')), 'NULL')
  #expect_type(get_chemical_lists_by_type(type = 'federal', API_key = ''), 'NULL')
  expect_type(get_public_chemical_list_by_name(list_name = 'BIOSOLIDS2021', API_key = Sys.getenv('CCTE_API_KEY')), 'list')
  expect_type(get_public_chemical_list_by_name(list_name = '', API_key = Sys.getenv('CCTE_API_KEY')), 'NULL')
  #expect_type(get_public_chemical_list_by_name(list_name = 'BIOSOLIDS2021', API_key = ''), 'NULL')
  expect_type(get_lists_containing_chemical(DTXSID = 'DTXSID7020182', API_key = Sys.getenv('CCTE_API_KEY')), 'character')
  expect_type(get_lists_containing_chemical(DTXSID = '', API_key = Sys.getenv('CCTE_API_KEY')), 'NULL')
  #expect_type(get_lists_containing_chemical(DTXSID = 'DTXSID7020182', API_key = ''), 'NULL')
  expect_type(get_chemicals_in_list(list_name = 'BIOSOLDIS2021', API_key = Sys.getenv('CCTE_API_KEY')), 'list')
  expect_type(get_chemicals_in_list(list_name = '', API_key = Sys.getenv('CCTE_API_KEY')), 'NULL')
  #expect_type(get_chemicals_in_list(list_name = 'BIOSOLDIS2021', API_key = ''), 'NULL')
  expect_type(get_all_public_chemical_lists(API_key = Sys.getenv('CCTE_API_KEY')), 'list')
  #expect_type(get_all_public_chemical_lists(API_key = ''), 'NULL')
  expect_type(get_chemical_mrv(DTXSID = 'DTXSID7020182', API_key = Sys.getenv('CCTE_API_KEY')), 'character')
  expect_type(get_chemical_mrv(DTXCID = 'DTXCID30182', API_key = Sys.getenv('CCTE_API_KEY')), 'character')
  expect_type(get_chemical_mrv(DTXSID = '', API_key = Sys.getenv('CCTE_API_KEY')), 'NULL')
  #expect_type(get_chemical_mrv(DTXSID = 'DTXSID7020182', API_key = ''), 'NULL')
  #expect_type(get_chemical_mrv(DTXCID = 'DTXCID30182', API_key = ''), 'NULL')
  expect_type(get_chemical_mol(DTXSID = 'DTXSID7020182', API_key = Sys.getenv('CCTE_API_KEY')), 'character')
  expect_type(get_chemical_mol(DTXCID = 'DTXCID30182', API_key = Sys.getenv('CCTE_API_KEY')), 'character')
  expect_type(get_chemical_mol(DTXSID = '', API_key = Sys.getenv('CCTE_API_KEY')), 'NULL')
  #expect_type(get_chemical_mol(DTXSID = 'DTXSID7020182', API_key = ''), 'NULL')
  #expect_type(get_chemical_mol(DTXCID = 'DTXCID30182', API_key = ''), 'NULL')
  expect_type(get_chemical_image(DTXSID = 'DTXSID7020182', API_key = Sys.getenv('CCTE_API_KEY')), 'double')
  expect_type(get_chemical_image(DTXCID = 'DTXCID30182', format = 'png', API_key = Sys.getenv('CCTE_API_KEY')), 'double')
  expect_type(get_chemical_image(DTXSID = '', format = 'svg', API_key = Sys.getenv('CCTE_API_KEY')), 'NULL')
  #expect_type(get_chemical_image(DTXSID = 'DTXSID7020182', API_key = ''), 'NULL')
  #expect_type(get_chemical_image(DTXCID = 'DTXCID30182', format = 'png', API_key = ''), 'NULL')
  expect_type(get_chemical_synonym(DTXSID = 'DTXSID7020182', API_key = Sys.getenv('CCTE_API_KEY')), 'list')
  expect_type(get_chemical_synonym(DTXSID = '', API_key = Sys.getenv('CCTE_API_KEY')), 'NULL')
  #expect_type(get_chemical_synonym(DTXSID = 'DTXSID7020182', API_key = ''), 'NULL')
})

test_that('check helper functions', {
  expect_equal(prepare_word('test'), 'test')
  expect_equal(prepare_word('test?'), 'test')
  expect_equal(prepare_word('test?test'), 'test?test=')
  expect_equal(prepare_word('test?test?'), 'test?test%3f=')
  expect_type(create_data.table_chemical_details(), 'list')
  expect_type(create_data.table_chemical_details(index = 3), 'list')
  expect_type(create_data.table_chemical_details(index = 4), 'list')
  expect_type(create_data.table_chemical_details(index = 5), 'list')
  expect_type(create_data.table_chemical_details(index = 6), 'list')
  expect_type(create_data.table_chemical_details(index = 'f'), 'list')
})
