structure(list(url = "https://api-ccte.epa.gov/exposure/functional-use/probability/search/by-dtxsid/", 
    status_code = 404L, headers = structure(list(`content-type` = "application/json", 
        `transfer-encoding` = "chunked", connection = "keep-alive", 
        date = "Mon, 22 Apr 2024 19:59:34 GMT", `cache-control` = "max-age=0, must-revalidate, no-transform", 
        `strict-transport-security` = "max-age=31536000", `x-content-type-options` = "nosniff", 
        `x-vcap-request-id` = "b72df0b8-ff02-400d-4451-21a42c2a9785", 
        `x-xss-protection` = "1; mode=block", `x-frame-options` = "DENY", 
        vary = "Accept-Encoding", `x-cache` = "Error from cloudfront", 
        via = "1.1 9c1465c390ec70cc0036cf15c3a531d8.cloudfront.net (CloudFront)", 
        `x-amz-cf-pop` = "EWR50-C1", `x-amz-cf-id` = "9Y8UJev-ZFQk2pj6hl_lL-u9Obi4m1yHZFpbONBti5MvsM72s5qXcQ=="), class = c("insensitive", 
    "list")), all_headers = list(list(status = 404L, version = "HTTP/1.1", 
        headers = structure(list(`content-type` = "application/json", 
            `transfer-encoding` = "chunked", connection = "keep-alive", 
            date = "Mon, 22 Apr 2024 19:59:34 GMT", `cache-control` = "max-age=0, must-revalidate, no-transform", 
            `strict-transport-security` = "max-age=31536000", 
            `x-content-type-options` = "nosniff", `x-vcap-request-id` = "b72df0b8-ff02-400d-4451-21a42c2a9785", 
            `x-xss-protection` = "1; mode=block", `x-frame-options` = "DENY", 
            vary = "Accept-Encoding", `x-cache` = "Error from cloudfront", 
            via = "1.1 9c1465c390ec70cc0036cf15c3a531d8.cloudfront.net (CloudFront)", 
            `x-amz-cf-pop` = "EWR50-C1", `x-amz-cf-id` = "9Y8UJev-ZFQk2pj6hl_lL-u9Obi4m1yHZFpbONBti5MvsM72s5qXcQ=="), class = c("insensitive", 
        "list")))), cookies = structure(list(domain = logical(0), 
        flag = logical(0), path = logical(0), secure = logical(0), 
        expiration = structure(numeric(0), class = c("POSIXct", 
        "POSIXt")), name = logical(0), value = logical(0)), row.names = integer(0), class = "data.frame"), 
    content = charToRaw("{\n  \"timestamp\" : \"2024-04-22T19:59:33.964+00:00\",\n  \"status\" : 404,\n  \"error\" : \"Not Found\",\n  \"path\" : \"/exposure/functional-use/probability/search/by-dtxsid/\"\n}"), 
    date = structure(1713815974, class = c("POSIXct", "POSIXt"
    ), tzone = "GMT"), times = c(redirect = 0, namelookup = 4.5e-05, 
    connect = 0, pretransfer = 0.000136, starttransfer = 0.219371, 
    total = 0.219408)), class = "response")
