structure(list(url = "https://api-ccte.epa.gov/exposure/httk/search/by-dtxsid/", 
    status_code = 404L, headers = structure(list(`content-type` = "application/json", 
        `transfer-encoding` = "chunked", connection = "keep-alive", 
        date = "Wed, 24 Jul 2024 11:46:20 GMT", `cache-control` = "max-age=0, must-revalidate, no-transform", 
        `strict-transport-security` = "max-age=31536000", `x-content-type-options` = "nosniff", 
        `x-vcap-request-id` = "7883c407-767b-4ad2-4405-57d6b427e8a1", 
        `x-xss-protection` = "1; mode=block", `x-frame-options` = "DENY", 
        vary = "Accept-Encoding", `x-cache` = "Error from cloudfront", 
        via = "1.1 3aed7f1651246872b9b4d9854870e1ca.cloudfront.net (CloudFront)", 
        `x-amz-cf-pop` = "DFW57-P7", `x-amz-cf-id` = "XCgPrCLtb-zDfkPtKSStOFc7twHz7HHa_Nxs2Zjhgwz8TEDx5F44tg=="), class = c("insensitive", 
    "list")), all_headers = list(list(status = 404L, version = "HTTP/1.1", 
        headers = structure(list(`content-type` = "application/json", 
            `transfer-encoding` = "chunked", connection = "keep-alive", 
            date = "Wed, 24 Jul 2024 11:46:20 GMT", `cache-control` = "max-age=0, must-revalidate, no-transform", 
            `strict-transport-security` = "max-age=31536000", 
            `x-content-type-options` = "nosniff", `x-vcap-request-id` = "7883c407-767b-4ad2-4405-57d6b427e8a1", 
            `x-xss-protection` = "1; mode=block", `x-frame-options` = "DENY", 
            vary = "Accept-Encoding", `x-cache` = "Error from cloudfront", 
            via = "1.1 3aed7f1651246872b9b4d9854870e1ca.cloudfront.net (CloudFront)", 
            `x-amz-cf-pop` = "DFW57-P7", `x-amz-cf-id` = "XCgPrCLtb-zDfkPtKSStOFc7twHz7HHa_Nxs2Zjhgwz8TEDx5F44tg=="), class = c("insensitive", 
        "list")))), cookies = structure(list(domain = logical(0), 
        flag = logical(0), path = logical(0), secure = logical(0), 
        expiration = structure(numeric(0), class = c("POSIXct", 
        "POSIXt")), name = logical(0), value = logical(0)), row.names = integer(0), class = "data.frame"), 
    content = charToRaw("{\n  \"timestamp\" : \"2024-07-24T11:46:21.000+00:00\",\n  \"status\" : 404,\n  \"error\" : \"Not Found\",\n  \"path\" : \"/exposure/httk/search/by-dtxsid/\"\n}"), 
    date = structure(1721821580, class = c("POSIXct", "POSIXt"
    ), tzone = "GMT"), times = c(redirect = 0, namelookup = 4.6e-05, 
    connect = 0, pretransfer = 0.000173, starttransfer = 0.215551, 
    total = 0.215611)), class = "response")
