structure(list(url = "https://api-ccte.epa.gov/bioactivity/search/by-dtxsid/", 
    status_code = 404L, headers = structure(list(`content-type` = "application/json", 
        `transfer-encoding` = "chunked", connection = "keep-alive", 
        date = "Thu, 15 Feb 2024 15:09:00 GMT", `x-vcap-request-id` = "4e74071b-b67e-40d4-795f-a074c2fc6d16", 
        `x-frame-options` = "DENY", `strict-transport-security` = "max-age=31536000", 
        `x-content-type-options` = "nosniff", `x-xss-protection` = "1; mode=block", 
        vary = "Accept-Encoding", `x-cache` = "Error from cloudfront", 
        via = "1.1 e832d261a0bb86f8ba09ea0550c8e77e.cloudfront.net (CloudFront)", 
        `x-amz-cf-pop` = "EWR53-P1", `x-amz-cf-id` = "3o2zbkdF1bK9P7y9q22yI7JNWwwozZGDFWYdnsSoPZuRay2g9Xs2TA=="), class = c("insensitive", 
    "list")), all_headers = list(list(status = 404L, version = "HTTP/1.1", 
        headers = structure(list(`content-type` = "application/json", 
            `transfer-encoding` = "chunked", connection = "keep-alive", 
            date = "Thu, 15 Feb 2024 15:09:00 GMT", `x-vcap-request-id` = "4e74071b-b67e-40d4-795f-a074c2fc6d16", 
            `x-frame-options` = "DENY", `strict-transport-security` = "max-age=31536000", 
            `x-content-type-options` = "nosniff", `x-xss-protection` = "1; mode=block", 
            vary = "Accept-Encoding", `x-cache` = "Error from cloudfront", 
            via = "1.1 e832d261a0bb86f8ba09ea0550c8e77e.cloudfront.net (CloudFront)", 
            `x-amz-cf-pop` = "EWR53-P1", `x-amz-cf-id` = "3o2zbkdF1bK9P7y9q22yI7JNWwwozZGDFWYdnsSoPZuRay2g9Xs2TA=="), class = c("insensitive", 
        "list")))), cookies = structure(list(domain = logical(0), 
        flag = logical(0), path = logical(0), secure = logical(0), 
        expiration = structure(numeric(0), class = c("POSIXct", 
        "POSIXt")), name = logical(0), value = logical(0)), row.names = integer(0), class = "data.frame"), 
    content = charToRaw("{\n  \"timestamp\" : \"2024-02-15T15:09:00.195+00:00\",\n  \"status\" : 404,\n  \"error\" : \"Not Found\",\n  \"path\" : \"/bioactivity/search/by-dtxsid/\"\n}"), 
    date = structure(1708009740, class = c("POSIXct", "POSIXt"
    ), tzone = "GMT"), times = c(redirect = 0, namelookup = 4.5e-05, 
    connect = 0, pretransfer = 0.00012, starttransfer = 0.23245, 
    total = 0.23248)), class = "response")
