structure(list(url = "https://api-ccte.epa.gov/chemical/list/search/by-dtxsid/", 
    status_code = 404L, headers = structure(list(`content-type` = "text/html;charset=utf-8", 
        `content-length` = "431", connection = "keep-alive", 
        date = "Thu, 15 Feb 2024 20:55:56 GMT", `content-language` = "en", 
        `x-vcap-request-id` = "476cece9-fe91-4ba0-75c9-e89b481e6050", 
        `x-frame-options` = "DENY", `strict-transport-security` = "max-age=31536000", 
        `x-content-type-options` = "nosniff", `x-xss-protection` = "1; mode=block", 
        vary = "Accept-Encoding", `x-cache` = "Error from cloudfront", 
        via = "1.1 2ba01a121d51ee735a8dde7a86ed73b6.cloudfront.net (CloudFront)", 
        `x-amz-cf-pop` = "EWR53-P1", `x-amz-cf-id` = "7dbAobyoCcMvws5ylqt97WV0DdXeTD4D2hkt2xUdSY7yPNG0Sd-NyQ=="), class = c("insensitive", 
    "list")), all_headers = list(list(status = 404L, version = "HTTP/1.1", 
        headers = structure(list(`content-type` = "text/html;charset=utf-8", 
            `content-length` = "431", connection = "keep-alive", 
            date = "Thu, 15 Feb 2024 20:55:56 GMT", `content-language` = "en", 
            `x-vcap-request-id` = "476cece9-fe91-4ba0-75c9-e89b481e6050", 
            `x-frame-options` = "DENY", `strict-transport-security` = "max-age=31536000", 
            `x-content-type-options` = "nosniff", `x-xss-protection` = "1; mode=block", 
            vary = "Accept-Encoding", `x-cache` = "Error from cloudfront", 
            via = "1.1 2ba01a121d51ee735a8dde7a86ed73b6.cloudfront.net (CloudFront)", 
            `x-amz-cf-pop` = "EWR53-P1", `x-amz-cf-id` = "7dbAobyoCcMvws5ylqt97WV0DdXeTD4D2hkt2xUdSY7yPNG0Sd-NyQ=="), class = c("insensitive", 
        "list")))), cookies = structure(list(domain = logical(0), 
        flag = logical(0), path = logical(0), secure = logical(0), 
        expiration = structure(numeric(0), class = c("POSIXct", 
        "POSIXt")), name = logical(0), value = logical(0)), row.names = integer(0), class = "data.frame"), 
    content = charToRaw("<!doctype html><html lang=\"en\"><head><title>HTTP Status 404 – Not Found</title><style type=\"text/css\">body {font-family:Tahoma,Arial,sans-serif;} h1, h2, h3, b {color:white;background-color:#525D76;} h1 {font-size:22px;} h2 {font-size:16px;} h3 {font-size:14px;} p {font-size:12px;} a {color:black;} .line {height:1px;background-color:#525D76;border:none;}</style></head><body><h1>HTTP Status 404 – Not Found</h1></body></html>"), 
    date = structure(1708030556, class = c("POSIXct", "POSIXt"
    ), tzone = "GMT"), times = c(redirect = 0, namelookup = 3.9e-05, 
    connect = 0, pretransfer = 0.000119, starttransfer = 0.235596, 
    total = 0.23563)), class = "response")
