structure(list(url = "https://api-ccte.epa.gov/chemical/property/search/by-dtxsid/", 
    status_code = 401L, headers = structure(list(`content-type` = "application/json;charset=ISO-8859-1", 
        `content-length` = "164", connection = "keep-alive", 
        date = "Wed, 27 Mar 2024 17:45:12 GMT", `x-vcap-request-id` = "f30a3474-83ea-4e71-499b-3574df6e2d3b", 
        `x-frame-options` = "DENY", `strict-transport-security` = "max-age=31536000", 
        `x-content-type-options` = "nosniff", `x-xss-protection` = "1; mode=block", 
        `x-cache` = "Error from cloudfront", via = "1.1 1da54da545c8e5f7d6ae32691691f7aa.cloudfront.net (CloudFront)", 
        `x-amz-cf-pop` = "ATL59-P8", `x-amz-cf-id` = "of_XtT3L4fdQ5qZnQIupjsYjpk5hoTvDDyPvFWnQ5ePRIx65rKB36g=="), class = c("insensitive", 
    "list")), all_headers = list(list(status = 401L, version = "HTTP/1.1", 
        headers = structure(list(`content-type` = "application/json;charset=ISO-8859-1", 
            `content-length` = "164", connection = "keep-alive", 
            date = "Wed, 27 Mar 2024 17:45:12 GMT", `x-vcap-request-id` = "f30a3474-83ea-4e71-499b-3574df6e2d3b", 
            `x-frame-options` = "DENY", `strict-transport-security` = "max-age=31536000", 
            `x-content-type-options` = "nosniff", `x-xss-protection` = "1; mode=block", 
            `x-cache` = "Error from cloudfront", via = "1.1 1da54da545c8e5f7d6ae32691691f7aa.cloudfront.net (CloudFront)", 
            `x-amz-cf-pop` = "ATL59-P8", `x-amz-cf-id` = "of_XtT3L4fdQ5qZnQIupjsYjpk5hoTvDDyPvFWnQ5ePRIx65rKB36g=="), class = c("insensitive", 
        "list")))), cookies = structure(list(domain = logical(0), 
        flag = logical(0), path = logical(0), secure = logical(0), 
        expiration = structure(numeric(0), class = c("POSIXct", 
        "POSIXt")), name = logical(0), value = logical(0)), row.names = integer(0), class = "data.frame"), 
    content = charToRaw("{\"title\":\"API Header Not Found\",\"detail\":\"Every API call should pass assigned API key through custom http header or query parameter. Request is missing x-api-key.\"}"), 
    date = structure(1711561512, class = c("POSIXct", "POSIXt"
    ), tzone = "GMT"), times = c(redirect = 0, namelookup = 4e-05, 
    connect = 0, pretransfer = 0.000161, starttransfer = 0.105628, 
    total = 0.105656)), class = "response")
