structure(list(url = "https://api-ccte.epa.gov/exposure/product-data/search/by-dtxsid/", 
    status_code = 404L, headers = structure(list(`content-type` = "application/json", 
        `transfer-encoding` = "chunked", connection = "keep-alive", 
        date = "Thu, 18 Sep 2025 18:19:18 GMT", `x-vcap-request-id` = "a44b0596-daf6-40f8-5194-ff17ab1a4524", 
        `x-frame-options` = "DENY", `cache-control` = "max-age=0, must-revalidate, no-transform", 
        `strict-transport-security` = "max-age=31536000", `x-content-type-options` = "nosniff", 
        vary = "Accept-Encoding", `x-cache` = "Error from cloudfront", 
        via = "1.1 2809a14efb112c83ea78308be199c466.cloudfront.net (CloudFront)", 
        `x-amz-cf-pop` = "ATL59-P8", `x-amz-cf-id` = "OTlezzFVvMY7z8oDWCigdZ1IU3klKOiH2TAu5b4Dvm-zM_V8fLp0kg=="), class = c("insensitive", 
    "list")), all_headers = list(list(status = 404L, version = "HTTP/1.1", 
        headers = structure(list(`content-type` = "application/json", 
            `transfer-encoding` = "chunked", connection = "keep-alive", 
            date = "Thu, 18 Sep 2025 18:19:18 GMT", `x-vcap-request-id` = "a44b0596-daf6-40f8-5194-ff17ab1a4524", 
            `x-frame-options` = "DENY", `cache-control` = "max-age=0, must-revalidate, no-transform", 
            `strict-transport-security` = "max-age=31536000", 
            `x-content-type-options` = "nosniff", vary = "Accept-Encoding", 
            `x-cache` = "Error from cloudfront", via = "1.1 2809a14efb112c83ea78308be199c466.cloudfront.net (CloudFront)", 
            `x-amz-cf-pop` = "ATL59-P8", `x-amz-cf-id` = "OTlezzFVvMY7z8oDWCigdZ1IU3klKOiH2TAu5b4Dvm-zM_V8fLp0kg=="), class = c("insensitive", 
        "list")))), cookies = structure(list(domain = logical(0), 
        flag = logical(0), path = logical(0), secure = logical(0), 
        expiration = structure(numeric(0), class = c("POSIXct", 
        "POSIXt")), name = logical(0), value = logical(0)), row.names = integer(0), class = "data.frame"), 
    content = charToRaw("{\n  \"timestamp\" : \"2025-09-18T18:19:18.717+00:00\",\n  \"status\" : 404,\n  \"error\" : \"Not Found\",\n  \"path\" : \"/exposure/product-data/search/by-dtxsid/\"\n}"), 
    date = structure(1758219558, class = c("POSIXct", "POSIXt"
    ), tzone = "GMT"), times = c(redirect = 0, namelookup = 3.7e-05, 
    connect = 0, pretransfer = 0.000168, starttransfer = 0.11289, 
    total = 0.11296)), class = "response")
