structure(list(url = "https://api-ccte.epa.gov/hazard/search/by-dtxsid/", 
    status_code = 401L, headers = structure(list(`content-type` = "application/json;charset=ISO-8859-1", 
        `content-length` = "164", connection = "keep-alive", 
        date = "Thu, 15 Feb 2024 14:14:51 GMT", `x-vcap-request-id` = "8aecf829-f4e8-4697-6f86-5fa235422a88", 
        `x-frame-options` = "DENY", `strict-transport-security` = "max-age=31536000", 
        `x-content-type-options` = "nosniff", `x-xss-protection` = "1; mode=block", 
        `x-cache` = "Error from cloudfront", via = "1.1 1baed9857df8e3a07a6cd7cd51feb3f8.cloudfront.net (CloudFront)", 
        `x-amz-cf-pop` = "EWR53-P1", `x-amz-cf-id` = "8WETfY_R2ygILLunGhVG6JIoOJDt_Go9DibCs6jKElRa6iERq9-eaw=="), class = c("insensitive", 
    "list")), all_headers = list(list(status = 401L, version = "HTTP/1.1", 
        headers = structure(list(`content-type` = "application/json;charset=ISO-8859-1", 
            `content-length` = "164", connection = "keep-alive", 
            date = "Thu, 15 Feb 2024 14:14:51 GMT", `x-vcap-request-id` = "8aecf829-f4e8-4697-6f86-5fa235422a88", 
            `x-frame-options` = "DENY", `strict-transport-security` = "max-age=31536000", 
            `x-content-type-options` = "nosniff", `x-xss-protection` = "1; mode=block", 
            `x-cache` = "Error from cloudfront", via = "1.1 1baed9857df8e3a07a6cd7cd51feb3f8.cloudfront.net (CloudFront)", 
            `x-amz-cf-pop` = "EWR53-P1", `x-amz-cf-id` = "8WETfY_R2ygILLunGhVG6JIoOJDt_Go9DibCs6jKElRa6iERq9-eaw=="), class = c("insensitive", 
        "list")))), cookies = structure(list(domain = logical(0), 
        flag = logical(0), path = logical(0), secure = logical(0), 
        expiration = structure(numeric(0), class = c("POSIXct", 
        "POSIXt")), name = logical(0), value = logical(0)), row.names = integer(0), class = "data.frame"), 
    content = charToRaw("{\"title\":\"API Header Not Found\",\"detail\":\"Every API call should pass assigned API key through custom http header or query parameter. Request is missing x-api-key.\"}"), 
    date = structure(1708006491, class = c("POSIXct", "POSIXt"
    ), tzone = "GMT"), times = c(redirect = 0, namelookup = 5.8e-05, 
    connect = 0, pretransfer = 0.000123, starttransfer = 0.090369, 
    total = 0.090413)), class = "response")
