structure(list(url = "https://comptox.epa.gov/ctx-api/bioactivity/assay/search/by-endpoint/?endpoint=", 
    status_code = 200L, headers = structure(list(date = "Thu, 07 May 2026 19:52:37 GMT", 
        server = "Apache", `strict-transport-security` = "max-age=63072000; includeSubDomains; preload“", 
        `access-control-allow-origin` = "*", vary = "Origin,Access-Control-Request-Method,Access-Control-Request-Headers", 
        `cache-control` = "no-cache, must-revalidate", `content-length` = "0"), class = c("insensitive", 
    "list")), all_headers = list(list(status = 200L, version = "HTTP/1.1", 
        headers = structure(list(date = "Thu, 07 May 2026 19:52:37 GMT", 
            server = "Apache", `strict-transport-security` = "max-age=63072000; includeSubDomains; preload“", 
            `access-control-allow-origin` = "*", vary = "Origin,Access-Control-Request-Method,Access-Control-Request-Headers", 
            `cache-control` = "no-cache, must-revalidate", `content-length` = "0"), class = c("insensitive", 
        "list")))), cookies = structure(list(domain = logical(0), 
        flag = logical(0), path = logical(0), secure = logical(0), 
        expiration = structure(numeric(0), class = c("POSIXct", 
        "POSIXt")), name = logical(0), value = logical(0)), row.names = integer(0), class = "data.frame"), 
    content = raw(0), date = structure(1778183557, class = c("POSIXct", 
    "POSIXt"), tzone = "GMT"), times = c(redirect = 0, namelookup = 4.1e-05, 
    connect = 0, pretransfer = 0.000179, starttransfer = 0.039413, 
    total = 0.03948)), class = "response")
