structure(list(url = "https://api-ccte.epa.gov/chemical/file/mrv/search/by-dtxsid/", 
    status_code = 404L, headers = structure(list(`content-type` = "text/html;charset=utf-8", 
        `content-length` = "431", connection = "keep-alive", 
        date = "Thu, 15 Feb 2024 20:56:01 GMT", `content-language` = "en", 
        `x-vcap-request-id` = "bd5aefa6-084a-424d-4bd2-7cff9b3cb9b9", 
        `x-frame-options` = "DENY", `strict-transport-security` = "max-age=31536000", 
        `x-content-type-options` = "nosniff", `x-xss-protection` = "1; mode=block", 
        vary = "Accept-Encoding", `x-cache` = "Error from cloudfront", 
        via = "1.1 2ba01a121d51ee735a8dde7a86ed73b6.cloudfront.net (CloudFront)", 
        `x-amz-cf-pop` = "EWR53-P1", `x-amz-cf-id` = "CJ1YfkVWWgiNSiB7clV_l9vRF3jQZArEl1mHYj8ohyY5MyO6dKOfDQ=="), class = c("insensitive", 
    "list")), all_headers = list(list(status = 404L, version = "HTTP/1.1", 
        headers = structure(list(`content-type` = "text/html;charset=utf-8", 
            `content-length` = "431", connection = "keep-alive", 
            date = "Thu, 15 Feb 2024 20:56:01 GMT", `content-language` = "en", 
            `x-vcap-request-id` = "bd5aefa6-084a-424d-4bd2-7cff9b3cb9b9", 
            `x-frame-options` = "DENY", `strict-transport-security` = "max-age=31536000", 
            `x-content-type-options` = "nosniff", `x-xss-protection` = "1; mode=block", 
            vary = "Accept-Encoding", `x-cache` = "Error from cloudfront", 
            via = "1.1 2ba01a121d51ee735a8dde7a86ed73b6.cloudfront.net (CloudFront)", 
            `x-amz-cf-pop` = "EWR53-P1", `x-amz-cf-id` = "CJ1YfkVWWgiNSiB7clV_l9vRF3jQZArEl1mHYj8ohyY5MyO6dKOfDQ=="), class = c("insensitive", 
        "list")))), cookies = structure(list(domain = logical(0), 
        flag = logical(0), path = logical(0), secure = logical(0), 
        expiration = structure(numeric(0), class = c("POSIXct", 
        "POSIXt")), name = logical(0), value = logical(0)), row.names = integer(0), class = "data.frame"), 
    content = charToRaw("<!doctype html><html lang=\"en\"><head><title>HTTP Status 404 – Not Found</title><style type=\"text/css\">body {font-family:Tahoma,Arial,sans-serif;} h1, h2, h3, b {color:white;background-color:#525D76;} h1 {font-size:22px;} h2 {font-size:16px;} h3 {font-size:14px;} p {font-size:12px;} a {color:black;} .line {height:1px;background-color:#525D76;border:none;}</style></head><body><h1>HTTP Status 404 – Not Found</h1></body></html>"), 
    date = structure(1708030561, class = c("POSIXct", "POSIXt"
    ), tzone = "GMT"), times = c(redirect = 0, namelookup = 2.7e-05, 
    connect = 0, pretransfer = 8.3e-05, starttransfer = 0.240732, 
    total = 0.240778)), class = "response")
