structure(list(url = "https://api-ccte.epa.gov/exposure/list-presence/search/by-dtxsid/", 
    status_code = 404L, headers = structure(list(`content-type` = "application/json", 
        `transfer-encoding` = "chunked", connection = "keep-alive", 
        date = "Thu, 18 Sep 2025 19:25:54 GMT", `x-vcap-request-id` = "4401f1fb-7507-4bba-765c-cd78523f2f15", 
        `x-frame-options` = "DENY", `cache-control` = "max-age=0, must-revalidate, no-transform", 
        `strict-transport-security` = "max-age=31536000", `x-content-type-options` = "nosniff", 
        vary = "Accept-Encoding", `x-cache` = "Error from cloudfront", 
        via = "1.1 87fd86cc57c26e58e2dfe4914bc636f6.cloudfront.net (CloudFront)", 
        `x-amz-cf-pop` = "ATL59-P8", `x-amz-cf-id` = "J4y_PFkcZoeolMgXCSIu4HNImb8mPJaXta6FVRoORQgRLuhstcdGQQ=="), class = c("insensitive", 
    "list")), all_headers = list(list(status = 404L, version = "HTTP/1.1", 
        headers = structure(list(`content-type` = "application/json", 
            `transfer-encoding` = "chunked", connection = "keep-alive", 
            date = "Thu, 18 Sep 2025 19:25:54 GMT", `x-vcap-request-id` = "4401f1fb-7507-4bba-765c-cd78523f2f15", 
            `x-frame-options` = "DENY", `cache-control` = "max-age=0, must-revalidate, no-transform", 
            `strict-transport-security` = "max-age=31536000", 
            `x-content-type-options` = "nosniff", vary = "Accept-Encoding", 
            `x-cache` = "Error from cloudfront", via = "1.1 87fd86cc57c26e58e2dfe4914bc636f6.cloudfront.net (CloudFront)", 
            `x-amz-cf-pop` = "ATL59-P8", `x-amz-cf-id` = "J4y_PFkcZoeolMgXCSIu4HNImb8mPJaXta6FVRoORQgRLuhstcdGQQ=="), class = c("insensitive", 
        "list")))), cookies = structure(list(domain = logical(0), 
        flag = logical(0), path = logical(0), secure = logical(0), 
        expiration = structure(numeric(0), class = c("POSIXct", 
        "POSIXt")), name = logical(0), value = logical(0)), row.names = integer(0), class = "data.frame"), 
    content = charToRaw("{\n  \"timestamp\" : \"2025-09-18T19:25:54.524+00:00\",\n  \"status\" : 404,\n  \"error\" : \"Not Found\",\n  \"path\" : \"/exposure/list-presence/search/by-dtxsid/\"\n}"), 
    date = structure(1758223554, class = c("POSIXct", "POSIXt"
    ), tzone = "GMT"), times = c(redirect = 0, namelookup = 9.1e-05, 
    connect = 0, pretransfer = 0.000282, starttransfer = 0.114188, 
    total = 0.114259)), class = "response")
