structure(list(url = "https://api-ccte.epa.gov/chemical/detail/search/by-dtxsid/?projection=chemicaldetailstandard", 
    status_code = 401L, headers = structure(list(`content-type` = "application/json;charset=ISO-8859-1", 
        `content-length` = "164", connection = "keep-alive", 
        date = "Thu, 15 Feb 2024 14:13:08 GMT", `x-vcap-request-id` = "99d0e3d0-796a-4786-6b25-14155d5e80e1", 
        `x-frame-options` = "DENY", `strict-transport-security` = "max-age=31536000", 
        `x-content-type-options` = "nosniff", `x-xss-protection` = "1; mode=block", 
        `x-cache` = "Error from cloudfront", via = "1.1 34deee8ac34d726c1404a3045667664a.cloudfront.net (CloudFront)", 
        `x-amz-cf-pop` = "EWR53-P1", `x-amz-cf-id` = "aID_WnhHsSNXR9FlTutsSVpPgHu886ugCKivOSonnC8H-d7eMep7Hg=="), class = c("insensitive", 
    "list")), all_headers = list(list(status = 401L, version = "HTTP/1.1", 
        headers = structure(list(`content-type` = "application/json;charset=ISO-8859-1", 
            `content-length` = "164", connection = "keep-alive", 
            date = "Thu, 15 Feb 2024 14:13:08 GMT", `x-vcap-request-id` = "99d0e3d0-796a-4786-6b25-14155d5e80e1", 
            `x-frame-options` = "DENY", `strict-transport-security` = "max-age=31536000", 
            `x-content-type-options` = "nosniff", `x-xss-protection` = "1; mode=block", 
            `x-cache` = "Error from cloudfront", via = "1.1 34deee8ac34d726c1404a3045667664a.cloudfront.net (CloudFront)", 
            `x-amz-cf-pop` = "EWR53-P1", `x-amz-cf-id` = "aID_WnhHsSNXR9FlTutsSVpPgHu886ugCKivOSonnC8H-d7eMep7Hg=="), class = c("insensitive", 
        "list")))), cookies = structure(list(domain = logical(0), 
        flag = logical(0), path = logical(0), secure = logical(0), 
        expiration = structure(numeric(0), class = c("POSIXct", 
        "POSIXt")), name = logical(0), value = logical(0)), row.names = integer(0), class = "data.frame"), 
    content = charToRaw("{\"title\":\"API Header Not Found\",\"detail\":\"Every API call should pass assigned API key through custom http header or query parameter. Request is missing x-api-key.\"}"), 
    date = structure(1708006388, class = c("POSIXct", "POSIXt"
    ), tzone = "GMT"), times = c(redirect = 0, namelookup = 4.1e-05, 
    connect = 0, pretransfer = 0.000114, starttransfer = 0.091382, 
    total = 0.09141)), class = "response")
