structure(list(url = "https://api-ccte.epa.gov/exposure/seem/general/search/by-dtxsid/", 
    status_code = 404L, headers = structure(list(`content-type` = "application/json", 
        `transfer-encoding` = "chunked", connection = "keep-alive", 
        date = "Wed, 24 Jul 2024 11:45:49 GMT", `cache-control` = "max-age=0, must-revalidate, no-transform", 
        `strict-transport-security` = "max-age=31536000", `x-content-type-options` = "nosniff", 
        `x-vcap-request-id` = "cadfcb0d-da18-4810-499d-00dfad6daf88", 
        `x-xss-protection` = "1; mode=block", `x-frame-options` = "DENY", 
        vary = "Accept-Encoding", `x-cache` = "Error from cloudfront", 
        via = "1.1 42db90f4dde6e794d9f54fbf20063d7e.cloudfront.net (CloudFront)", 
        `x-amz-cf-pop` = "DFW57-P7", `x-amz-cf-id` = "bESCmIXOnemJDZupCFOX9xGOjS9uuhttKg5DWicAKfHGLGmGeMJLvg=="), class = c("insensitive", 
    "list")), all_headers = list(list(status = 404L, version = "HTTP/1.1", 
        headers = structure(list(`content-type` = "application/json", 
            `transfer-encoding` = "chunked", connection = "keep-alive", 
            date = "Wed, 24 Jul 2024 11:45:49 GMT", `cache-control` = "max-age=0, must-revalidate, no-transform", 
            `strict-transport-security` = "max-age=31536000", 
            `x-content-type-options` = "nosniff", `x-vcap-request-id` = "cadfcb0d-da18-4810-499d-00dfad6daf88", 
            `x-xss-protection` = "1; mode=block", `x-frame-options` = "DENY", 
            vary = "Accept-Encoding", `x-cache` = "Error from cloudfront", 
            via = "1.1 42db90f4dde6e794d9f54fbf20063d7e.cloudfront.net (CloudFront)", 
            `x-amz-cf-pop` = "DFW57-P7", `x-amz-cf-id` = "bESCmIXOnemJDZupCFOX9xGOjS9uuhttKg5DWicAKfHGLGmGeMJLvg=="), class = c("insensitive", 
        "list")))), cookies = structure(list(domain = logical(0), 
        flag = logical(0), path = logical(0), secure = logical(0), 
        expiration = structure(numeric(0), class = c("POSIXct", 
        "POSIXt")), name = logical(0), value = logical(0)), row.names = integer(0), class = "data.frame"), 
    content = charToRaw("{\n  \"timestamp\" : \"2024-07-24T11:45:49.395+00:00\",\n  \"status\" : 404,\n  \"error\" : \"Not Found\",\n  \"path\" : \"/exposure/seem/general/search/by-dtxsid/\"\n}"), 
    date = structure(1721821549, class = c("POSIXct", "POSIXt"
    ), tzone = "GMT"), times = c(redirect = 0, namelookup = 4.5e-05, 
    connect = 0, pretransfer = 0.000162, starttransfer = 0.225309, 
    total = 0.225339)), class = "response")
