structure(list(url = "https://api-ccte.epa.gov/exposure/httk/search/by-dtxsid/", 
    status_code = 404L, headers = structure(list(`content-type` = "application/json", 
        `transfer-encoding` = "chunked", connection = "keep-alive", 
        date = "Thu, 18 Sep 2025 17:59:12 GMT", `x-vcap-request-id` = "630ca6fb-bf03-40c4-6ea8-94260a38d003", 
        `x-frame-options` = "DENY", `cache-control` = "max-age=0, must-revalidate, no-transform", 
        `strict-transport-security` = "max-age=31536000", `x-content-type-options` = "nosniff", 
        vary = "Accept-Encoding", `x-cache` = "Error from cloudfront", 
        via = "1.1 7b0365f549e6b2fbadd8ec20314cbda0.cloudfront.net (CloudFront)", 
        `x-amz-cf-pop` = "ATL59-P8", `x-amz-cf-id` = "WfVQ_TZYbqcvU0h0nMTEw6J7bOmW0X5rkXrQLKhxWdCjKvGO8CZFIQ=="), class = c("insensitive", 
    "list")), all_headers = list(list(status = 404L, version = "HTTP/1.1", 
        headers = structure(list(`content-type` = "application/json", 
            `transfer-encoding` = "chunked", connection = "keep-alive", 
            date = "Thu, 18 Sep 2025 17:59:12 GMT", `x-vcap-request-id` = "630ca6fb-bf03-40c4-6ea8-94260a38d003", 
            `x-frame-options` = "DENY", `cache-control` = "max-age=0, must-revalidate, no-transform", 
            `strict-transport-security` = "max-age=31536000", 
            `x-content-type-options` = "nosniff", vary = "Accept-Encoding", 
            `x-cache` = "Error from cloudfront", via = "1.1 7b0365f549e6b2fbadd8ec20314cbda0.cloudfront.net (CloudFront)", 
            `x-amz-cf-pop` = "ATL59-P8", `x-amz-cf-id` = "WfVQ_TZYbqcvU0h0nMTEw6J7bOmW0X5rkXrQLKhxWdCjKvGO8CZFIQ=="), class = c("insensitive", 
        "list")))), cookies = structure(list(domain = logical(0), 
        flag = logical(0), path = logical(0), secure = logical(0), 
        expiration = structure(numeric(0), class = c("POSIXct", 
        "POSIXt")), name = logical(0), value = logical(0)), row.names = integer(0), class = "data.frame"), 
    content = charToRaw("{\n  \"timestamp\" : \"2025-09-18T17:59:12.855+00:00\",\n  \"status\" : 404,\n  \"error\" : \"Not Found\",\n  \"path\" : \"/exposure/httk/search/by-dtxsid/\"\n}"), 
    date = structure(1758218352, class = c("POSIXct", "POSIXt"
    ), tzone = "GMT"), times = c(redirect = 0, namelookup = 4.7e-05, 
    connect = 0, pretransfer = 0.000203, starttransfer = 0.114114, 
    total = 0.11415)), class = "response")
