structure(list(url = "https://api-ccte.epa.gov/bioactivity/search/by-aeid/1", 
    status_code = 401L, headers = structure(list(`content-type` = "application/json;charset=ISO-8859-1", 
        `content-length` = "121", connection = "keep-alive", 
        date = "Wed, 27 Mar 2024 17:15:33 GMT", `x-vcap-request-id` = "05d1492b-0c60-445d-63b7-25285e8fdf29", 
        `x-frame-options` = "DENY", `strict-transport-security` = "max-age=31536000", 
        `x-content-type-options` = "nosniff", `x-xss-protection` = "1; mode=block", 
        `x-cache` = "Error from cloudfront", via = "1.1 933ff1cca50cf69615381c805530ec5e.cloudfront.net (CloudFront)", 
        `x-amz-cf-pop` = "ATL59-P8", `x-amz-cf-id` = "7ljbs9mNAtCJwgXpEaMkRIM5gskqXOOHawKcsEyTjJfvbZrqAsvC7Q=="), class = c("insensitive", 
    "list")), all_headers = list(list(status = 401L, version = "HTTP/1.1", 
        headers = structure(list(`content-type` = "application/json;charset=ISO-8859-1", 
            `content-length` = "121", connection = "keep-alive", 
            date = "Wed, 27 Mar 2024 17:15:33 GMT", `x-vcap-request-id` = "05d1492b-0c60-445d-63b7-25285e8fdf29", 
            `x-frame-options` = "DENY", `strict-transport-security` = "max-age=31536000", 
            `x-content-type-options` = "nosniff", `x-xss-protection` = "1; mode=block", 
            `x-cache` = "Error from cloudfront", via = "1.1 933ff1cca50cf69615381c805530ec5e.cloudfront.net (CloudFront)", 
            `x-amz-cf-pop` = "ATL59-P8", `x-amz-cf-id` = "7ljbs9mNAtCJwgXpEaMkRIM5gskqXOOHawKcsEyTjJfvbZrqAsvC7Q=="), class = c("insensitive", 
        "list")))), cookies = structure(list(domain = logical(0), 
        flag = logical(0), path = logical(0), secure = logical(0), 
        expiration = structure(numeric(0), class = c("POSIXct", 
        "POSIXt")), name = logical(0), value = logical(0)), row.names = integer(0), class = "data.frame"), 
    content = charToRaw("{\"title\":\"API Key Not Found\",\"detail\":\"Please contact API admin for requesting a valid API key. Key test_key not found.\"}"), 
    date = structure(1711559733, class = c("POSIXct", "POSIXt"
    ), tzone = "GMT"), times = c(redirect = 0, namelookup = 4.1e-05, 
    connect = 0, pretransfer = 0.000141, starttransfer = 0.261866, 
    total = 0.26192)), class = "response")
