structure(list(url = "https://api-ccte.epa.gov/bioactivity/search/by-aeid/1", 
    status_code = 401L, headers = structure(list(`content-type` = "application/json;charset=ISO-8859-1", 
        `content-length` = "121", connection = "keep-alive", 
        date = "Fri, 22 Mar 2024 12:54:12 GMT", `x-vcap-request-id` = "8e09c003-86cb-4e1e-6053-a51cd09a3113", 
        `x-frame-options` = "DENY", `strict-transport-security` = "max-age=31536000", 
        `x-content-type-options` = "nosniff", `x-xss-protection` = "1; mode=block", 
        `x-cache` = "Error from cloudfront", via = "1.1 43684cbde7a46ef5524f47bc4254eff8.cloudfront.net (CloudFront)", 
        `x-amz-cf-pop` = "ORD51-C4", `x-amz-cf-id` = "ojWfjdS6eSIxFWF5Hhrx84N0SOmKIWcKFs59Bs3oNMa9tzl90jGpow=="), class = c("insensitive", 
    "list")), all_headers = list(list(status = 401L, version = "HTTP/1.1", 
        headers = structure(list(`content-type` = "application/json;charset=ISO-8859-1", 
            `content-length` = "121", connection = "keep-alive", 
            date = "Fri, 22 Mar 2024 12:54:12 GMT", `x-vcap-request-id` = "8e09c003-86cb-4e1e-6053-a51cd09a3113", 
            `x-frame-options` = "DENY", `strict-transport-security` = "max-age=31536000", 
            `x-content-type-options` = "nosniff", `x-xss-protection` = "1; mode=block", 
            `x-cache` = "Error from cloudfront", via = "1.1 43684cbde7a46ef5524f47bc4254eff8.cloudfront.net (CloudFront)", 
            `x-amz-cf-pop` = "ORD51-C4", `x-amz-cf-id` = "ojWfjdS6eSIxFWF5Hhrx84N0SOmKIWcKFs59Bs3oNMa9tzl90jGpow=="), class = c("insensitive", 
        "list")))), cookies = structure(list(domain = logical(0), 
        flag = logical(0), path = logical(0), secure = logical(0), 
        expiration = structure(numeric(0), class = c("POSIXct", 
        "POSIXt")), name = logical(0), value = logical(0)), row.names = integer(0), class = "data.frame"), 
    content = charToRaw("{\"title\":\"API Key Not Found\",\"detail\":\"Please contact API admin for requesting a valid API key. Key test_key not found.\"}"), 
    date = structure(1711112052, class = c("POSIXct", "POSIXt"
    ), tzone = "GMT"), times = c(redirect = 0, namelookup = 5.7e-05, 
    connect = 0, pretransfer = 0.000221, starttransfer = 0.263044, 
    total = 0.263073)), class = "response")
