structure(list(url = "https://api-ccte.epa.gov/chemical/list/search/by-dtxsid/DTXSID7020182", 
    status_code = 401L, headers = structure(list(`content-type` = "application/json;charset=ISO-8859-1", 
        `content-length` = "164", connection = "keep-alive", 
        date = "Thu, 29 Aug 2024 19:35:56 GMT", `strict-transport-security` = "max-age=31536000", 
        `x-content-type-options` = "nosniff", `x-vcap-request-id` = "b9931bb2-7a0a-4ff1-413e-5e146b905a18", 
        `x-xss-protection` = "1; mode=block", `x-frame-options` = "DENY", 
        `x-cache` = "Error from cloudfront", via = "1.1 b5e757a7da6f6fe6261f56a8a9646880.cloudfront.net (CloudFront)", 
        `x-amz-cf-pop` = "IAD89-C1", `x-amz-cf-id` = "yQQ1PV38yNynkJ2OUJWGQZCfpZ0zL2FuF7wr5zcep4qVKRDodrIYDQ=="), class = c("insensitive", 
    "list")), all_headers = list(list(status = 401L, version = "HTTP/1.1", 
        headers = structure(list(`content-type` = "application/json;charset=ISO-8859-1", 
            `content-length` = "164", connection = "keep-alive", 
            date = "Thu, 29 Aug 2024 19:35:56 GMT", `strict-transport-security` = "max-age=31536000", 
            `x-content-type-options` = "nosniff", `x-vcap-request-id` = "b9931bb2-7a0a-4ff1-413e-5e146b905a18", 
            `x-xss-protection` = "1; mode=block", `x-frame-options` = "DENY", 
            `x-cache` = "Error from cloudfront", via = "1.1 b5e757a7da6f6fe6261f56a8a9646880.cloudfront.net (CloudFront)", 
            `x-amz-cf-pop` = "IAD89-C1", `x-amz-cf-id` = "yQQ1PV38yNynkJ2OUJWGQZCfpZ0zL2FuF7wr5zcep4qVKRDodrIYDQ=="), class = c("insensitive", 
        "list")))), cookies = structure(list(domain = logical(0), 
        flag = logical(0), path = logical(0), secure = logical(0), 
        expiration = structure(numeric(0), class = c("POSIXct", 
        "POSIXt")), name = logical(0), value = logical(0)), row.names = integer(0), class = "data.frame"), 
    content = charToRaw("{\"title\":\"API Header Not Found\",\"detail\":\"Every API call should pass assigned API key through custom http header or query parameter. Request is missing x-api-key.\"}"), 
    date = structure(1724960156, class = c("POSIXct", "POSIXt"
    ), tzone = "GMT"), times = c(redirect = 0, namelookup = 3.9e-05, 
    connect = 0, pretransfer = 0.000106, starttransfer = 0.123758, 
    total = 0.123783)), class = "response")
