structure(list(url = "https://api-ccte.epa.gov/chemical/list/search/by-dtxsid/DTXSID7020182", 
    status_code = 401L, headers = structure(list(`content-type` = "application/json;charset=ISO-8859-1", 
        `content-length` = "164", connection = "keep-alive", 
        date = "Fri, 22 Mar 2024 15:48:22 GMT", `x-vcap-request-id` = "3525fa17-85d1-48c1-51aa-c5f5e3efb19e", 
        `x-frame-options` = "DENY", `strict-transport-security` = "max-age=31536000", 
        `x-content-type-options` = "nosniff", `x-xss-protection` = "1; mode=block", 
        `x-cache` = "Error from cloudfront", via = "1.1 9d35ce6897d7f02042955443076a54de.cloudfront.net (CloudFront)", 
        `x-amz-cf-pop` = "EWR53-P1", `x-amz-cf-id` = "2HYbr4NaaI09FK0B2gpnt-vauPgnp59-WoGtF-PrhmBzr34PNYISag=="), class = c("insensitive", 
    "list")), all_headers = list(list(status = 401L, version = "HTTP/1.1", 
        headers = structure(list(`content-type` = "application/json;charset=ISO-8859-1", 
            `content-length` = "164", connection = "keep-alive", 
            date = "Fri, 22 Mar 2024 15:48:22 GMT", `x-vcap-request-id` = "3525fa17-85d1-48c1-51aa-c5f5e3efb19e", 
            `x-frame-options` = "DENY", `strict-transport-security` = "max-age=31536000", 
            `x-content-type-options` = "nosniff", `x-xss-protection` = "1; mode=block", 
            `x-cache` = "Error from cloudfront", via = "1.1 9d35ce6897d7f02042955443076a54de.cloudfront.net (CloudFront)", 
            `x-amz-cf-pop` = "EWR53-P1", `x-amz-cf-id` = "2HYbr4NaaI09FK0B2gpnt-vauPgnp59-WoGtF-PrhmBzr34PNYISag=="), class = c("insensitive", 
        "list")))), cookies = structure(list(domain = logical(0), 
        flag = logical(0), path = logical(0), secure = logical(0), 
        expiration = structure(numeric(0), class = c("POSIXct", 
        "POSIXt")), name = logical(0), value = logical(0)), row.names = integer(0), class = "data.frame"), 
    content = charToRaw("{\"title\":\"API Header Not Found\",\"detail\":\"Every API call should pass assigned API key through custom http header or query parameter. Request is missing x-api-key.\"}"), 
    date = structure(1711122502, class = c("POSIXct", "POSIXt"
    ), tzone = "GMT"), times = c(redirect = 0, namelookup = 4.1e-05, 
    connect = 0, pretransfer = 0.000101, starttransfer = 0.102908, 
    total = 0.10294)), class = "response")
