structure(list(url = "https://api-ccte.epa.gov/chemical/msready/search/by-formula/CH4", 
    status_code = 401L, headers = structure(list(`content-type` = "application/json;charset=ISO-8859-1", 
        `content-length` = "164", connection = "keep-alive", 
        date = "Wed, 27 Mar 2024 21:31:33 GMT", `x-vcap-request-id` = "0b2bab56-26a1-403a-7b38-efc714ee3a72", 
        `x-frame-options` = "DENY", `strict-transport-security` = "max-age=31536000", 
        `x-content-type-options` = "nosniff", `x-xss-protection` = "1; mode=block", 
        `x-cache` = "Error from cloudfront", via = "1.1 d3b019645d09c89af6e150e75be90942.cloudfront.net (CloudFront)", 
        `x-amz-cf-pop` = "ATL59-P8", `x-amz-cf-id` = "p5VcA1XZNNGmIHSZ2Vgo_noPoy_aVPgi-2RzCfX_icMbnpZiGR8jjw=="), class = c("insensitive", 
    "list")), all_headers = list(list(status = 401L, version = "HTTP/1.1", 
        headers = structure(list(`content-type` = "application/json;charset=ISO-8859-1", 
            `content-length` = "164", connection = "keep-alive", 
            date = "Wed, 27 Mar 2024 21:31:33 GMT", `x-vcap-request-id` = "0b2bab56-26a1-403a-7b38-efc714ee3a72", 
            `x-frame-options` = "DENY", `strict-transport-security` = "max-age=31536000", 
            `x-content-type-options` = "nosniff", `x-xss-protection` = "1; mode=block", 
            `x-cache` = "Error from cloudfront", via = "1.1 d3b019645d09c89af6e150e75be90942.cloudfront.net (CloudFront)", 
            `x-amz-cf-pop` = "ATL59-P8", `x-amz-cf-id` = "p5VcA1XZNNGmIHSZ2Vgo_noPoy_aVPgi-2RzCfX_icMbnpZiGR8jjw=="), class = c("insensitive", 
        "list")))), cookies = structure(list(domain = logical(0), 
        flag = logical(0), path = logical(0), secure = logical(0), 
        expiration = structure(numeric(0), class = c("POSIXct", 
        "POSIXt")), name = logical(0), value = logical(0)), row.names = integer(0), class = "data.frame"), 
    content = charToRaw("{\"title\":\"API Header Not Found\",\"detail\":\"Every API call should pass assigned API key through custom http header or query parameter. Request is missing x-api-key.\"}"), 
    date = structure(1711575093, class = c("POSIXct", "POSIXt"
    ), tzone = "GMT"), times = c(redirect = 0, namelookup = 4.2e-05, 
    connect = 0, pretransfer = 0.000166, starttransfer = 0.099076, 
    total = 0.099552)), class = "response")
