structure(list(url = "https://api-ccte.epa.gov/bioactivity/search/by-dtxsid/", 
    status_code = 404L, headers = structure(list(`content-type` = "application/json", 
        `transfer-encoding` = "chunked", connection = "keep-alive", 
        date = "Thu, 15 Feb 2024 20:48:09 GMT", `x-vcap-request-id` = "a7389d50-eda8-4fae-791d-79ed15e71444", 
        `x-frame-options` = "DENY", `strict-transport-security` = "max-age=31536000", 
        `x-content-type-options` = "nosniff", `x-xss-protection` = "1; mode=block", 
        vary = "Accept-Encoding", `x-cache` = "Error from cloudfront", 
        via = "1.1 0146c8129cacdacca96753291cf27ec4.cloudfront.net (CloudFront)", 
        `x-amz-cf-pop` = "EWR53-P1", `x-amz-cf-id` = "6qax3t2tEbq7tgpizistA_O_7EDAQSSAjWb2VwL1lLvyvfD3iKTIWw=="), class = c("insensitive", 
    "list")), all_headers = list(list(status = 404L, version = "HTTP/1.1", 
        headers = structure(list(`content-type` = "application/json", 
            `transfer-encoding` = "chunked", connection = "keep-alive", 
            date = "Thu, 15 Feb 2024 20:48:09 GMT", `x-vcap-request-id` = "a7389d50-eda8-4fae-791d-79ed15e71444", 
            `x-frame-options` = "DENY", `strict-transport-security` = "max-age=31536000", 
            `x-content-type-options` = "nosniff", `x-xss-protection` = "1; mode=block", 
            vary = "Accept-Encoding", `x-cache` = "Error from cloudfront", 
            via = "1.1 0146c8129cacdacca96753291cf27ec4.cloudfront.net (CloudFront)", 
            `x-amz-cf-pop` = "EWR53-P1", `x-amz-cf-id` = "6qax3t2tEbq7tgpizistA_O_7EDAQSSAjWb2VwL1lLvyvfD3iKTIWw=="), class = c("insensitive", 
        "list")))), cookies = structure(list(domain = logical(0), 
        flag = logical(0), path = logical(0), secure = logical(0), 
        expiration = structure(numeric(0), class = c("POSIXct", 
        "POSIXt")), name = logical(0), value = logical(0)), row.names = integer(0), class = "data.frame"), 
    content = charToRaw("{\n  \"timestamp\" : \"2024-02-15T20:48:09.464+00:00\",\n  \"status\" : 404,\n  \"error\" : \"Not Found\",\n  \"path\" : \"/bioactivity/search/by-dtxsid/\"\n}"), 
    date = structure(1708030089, class = c("POSIXct", "POSIXt"
    ), tzone = "GMT"), times = c(redirect = 0, namelookup = 4.2e-05, 
    connect = 0, pretransfer = 0.000103, starttransfer = 0.26713, 
    total = 0.267177)), class = "response")
