structure(list(url = "https://api-ccte.epa.gov/bioactivity/search/by-dtxsid/", 
    status_code = 404L, headers = structure(list(`content-type` = "application/json", 
        `transfer-encoding` = "chunked", connection = "keep-alive", 
        date = "Wed, 27 Mar 2024 17:20:42 GMT", `cache-control` = "no-cache, must-revalidate", 
        `x-vcap-request-id` = "cec59688-bb12-473e-77ef-f008d28eb469", 
        `x-frame-options` = "DENY", `strict-transport-security` = "max-age=31536000", 
        `x-content-type-options` = "nosniff", `x-xss-protection` = "1; mode=block", 
        vary = "Accept-Encoding", `x-cache` = "Error from cloudfront", 
        via = "1.1 51a9fe879233bcdaa87b146359af2e0c.cloudfront.net (CloudFront)", 
        `x-amz-cf-pop` = "ORD51-C4", `x-amz-cf-id` = "Sc8WMUD1o2g7SaQlF8FpJ47U5cSzQjvzxt_QRrkM-rdLCb95UmGGqw=="), class = c("insensitive", 
    "list")), all_headers = list(list(status = 404L, version = "HTTP/1.1", 
        headers = structure(list(`content-type` = "application/json", 
            `transfer-encoding` = "chunked", connection = "keep-alive", 
            date = "Wed, 27 Mar 2024 17:20:42 GMT", `cache-control` = "no-cache, must-revalidate", 
            `x-vcap-request-id` = "cec59688-bb12-473e-77ef-f008d28eb469", 
            `x-frame-options` = "DENY", `strict-transport-security` = "max-age=31536000", 
            `x-content-type-options` = "nosniff", `x-xss-protection` = "1; mode=block", 
            vary = "Accept-Encoding", `x-cache` = "Error from cloudfront", 
            via = "1.1 51a9fe879233bcdaa87b146359af2e0c.cloudfront.net (CloudFront)", 
            `x-amz-cf-pop` = "ORD51-C4", `x-amz-cf-id` = "Sc8WMUD1o2g7SaQlF8FpJ47U5cSzQjvzxt_QRrkM-rdLCb95UmGGqw=="), class = c("insensitive", 
        "list")))), cookies = structure(list(domain = logical(0), 
        flag = logical(0), path = logical(0), secure = logical(0), 
        expiration = structure(numeric(0), class = c("POSIXct", 
        "POSIXt")), name = logical(0), value = logical(0)), row.names = integer(0), class = "data.frame"), 
    content = charToRaw("{\n  \"timestamp\" : \"2024-03-27T17:20:42.847+00:00\",\n  \"status\" : 404,\n  \"error\" : \"Not Found\",\n  \"path\" : \"/bioactivity/search/by-dtxsid/\"\n}"), 
    date = structure(1711560042, class = c("POSIXct", "POSIXt"
    ), tzone = "GMT"), times = c(redirect = 0, namelookup = 3.9e-05, 
    connect = 0, pretransfer = 0.000135, starttransfer = 0.263322, 
    total = 0.26335)), class = "response")
