structure(list(url = "https://api-ccte.epa.gov/exposure/functional-use/search/by-dtxsid/", 
    status_code = 404L, headers = structure(list(`content-type` = "application/json", 
        `transfer-encoding` = "chunked", connection = "keep-alive", 
        date = "Wed, 24 Apr 2024 20:00:37 GMT", `cache-control` = "max-age=0, must-revalidate, no-transform", 
        `strict-transport-security` = "max-age=31536000", `x-content-type-options` = "nosniff", 
        `x-vcap-request-id` = "8382b4dc-a127-4460-68a5-637fe781538e", 
        `x-xss-protection` = "1; mode=block", `x-frame-options` = "DENY", 
        vary = "Accept-Encoding", `x-cache` = "Error from cloudfront", 
        via = "1.1 d3fbeb74a503a5fcf3e4ca458c365012.cloudfront.net (CloudFront)", 
        `x-amz-cf-pop` = "EWR50-C1", `x-amz-cf-id` = "lb5K3ZH7XC1OVXPAPMVlUsl999djZBvpfM-rQWBcXOLCIZdApH6X1Q=="), class = c("insensitive", 
    "list")), all_headers = list(list(status = 404L, version = "HTTP/1.1", 
        headers = structure(list(`content-type` = "application/json", 
            `transfer-encoding` = "chunked", connection = "keep-alive", 
            date = "Wed, 24 Apr 2024 20:00:37 GMT", `cache-control` = "max-age=0, must-revalidate, no-transform", 
            `strict-transport-security` = "max-age=31536000", 
            `x-content-type-options` = "nosniff", `x-vcap-request-id` = "8382b4dc-a127-4460-68a5-637fe781538e", 
            `x-xss-protection` = "1; mode=block", `x-frame-options` = "DENY", 
            vary = "Accept-Encoding", `x-cache` = "Error from cloudfront", 
            via = "1.1 d3fbeb74a503a5fcf3e4ca458c365012.cloudfront.net (CloudFront)", 
            `x-amz-cf-pop` = "EWR50-C1", `x-amz-cf-id` = "lb5K3ZH7XC1OVXPAPMVlUsl999djZBvpfM-rQWBcXOLCIZdApH6X1Q=="), class = c("insensitive", 
        "list")))), cookies = structure(list(domain = logical(0), 
        flag = logical(0), path = logical(0), secure = logical(0), 
        expiration = structure(numeric(0), class = c("POSIXct", 
        "POSIXt")), name = logical(0), value = logical(0)), row.names = integer(0), class = "data.frame"), 
    content = charToRaw("{\n  \"timestamp\" : \"2024-04-24T20:00:37.484+00:00\",\n  \"status\" : 404,\n  \"error\" : \"Not Found\",\n  \"path\" : \"/exposure/functional-use/search/by-dtxsid/\"\n}"), 
    date = structure(1713988837, class = c("POSIXct", "POSIXt"
    ), tzone = "GMT"), times = c(redirect = 0, namelookup = 6.9e-05, 
    connect = 0, pretransfer = 0.000222, starttransfer = 0.233149, 
    total = 0.233212)), class = "response")
