structure(list(url = "https://api-ccte.epa.gov/chemical/opsin/to-inchikey/Acetamide", 
    status_code = 200L, headers = structure(list(`content-type` = "application/json", 
        `content-length` = "27", connection = "keep-alive", date = "Tue, 21 May 2024 17:14:09 GMT", 
        `cache-control` = "max-age=0, must-revalidate, no-transform", 
        `strict-transport-security` = "max-age=31536000", `x-content-type-options` = "nosniff", 
        `x-vcap-request-id` = "4da057aa-4fec-4dc5-6217-30328429bf99", 
        `x-xss-protection` = "1; mode=block", `x-frame-options` = "DENY", 
        vary = "Accept-Encoding", `x-cache` = "Miss from cloudfront", 
        via = "1.1 d7b509440ac55e6d7b3c4c7ad48b08f2.cloudfront.net (CloudFront)", 
        `x-amz-cf-pop` = "IAH50-C2", `x-amz-cf-id` = "t4onRws52u43iZUB_h-iUFfkLS07OEHPkypG9n52GODVa31Eix3xuA=="), class = c("insensitive", 
    "list")), all_headers = list(list(status = 200L, version = "HTTP/1.1", 
        headers = structure(list(`content-type` = "application/json", 
            `content-length` = "27", connection = "keep-alive", 
            date = "Tue, 21 May 2024 17:14:09 GMT", `cache-control` = "max-age=0, must-revalidate, no-transform", 
            `strict-transport-security` = "max-age=31536000", 
            `x-content-type-options` = "nosniff", `x-vcap-request-id` = "4da057aa-4fec-4dc5-6217-30328429bf99", 
            `x-xss-protection` = "1; mode=block", `x-frame-options` = "DENY", 
            vary = "Accept-Encoding", `x-cache` = "Miss from cloudfront", 
            via = "1.1 d7b509440ac55e6d7b3c4c7ad48b08f2.cloudfront.net (CloudFront)", 
            `x-amz-cf-pop` = "IAH50-C2", `x-amz-cf-id` = "t4onRws52u43iZUB_h-iUFfkLS07OEHPkypG9n52GODVa31Eix3xuA=="), class = c("insensitive", 
        "list")))), cookies = structure(list(domain = logical(0), 
        flag = logical(0), path = logical(0), secure = logical(0), 
        expiration = structure(numeric(0), class = c("POSIXct", 
        "POSIXt")), name = logical(0), value = logical(0)), row.names = integer(0), class = "data.frame"), 
    content = charToRaw("DLFVBJFMPXGRIB-UHFFFAOYSA-N"), date = structure(1716311649, class = c("POSIXct", 
    "POSIXt"), tzone = "GMT"), times = c(redirect = 0, namelookup = 4.1e-05, 
    connect = 0, pretransfer = 0.000163, starttransfer = 0.115037, 
    total = 0.115074)), class = "response")
