structure(list(url = "https://api-ccte.epa.gov/exposure/functional-use/search/by-dtxsid/", 
    status_code = 404L, headers = structure(list(`content-type` = "application/json", 
        `transfer-encoding` = "chunked", connection = "keep-alive", 
        date = "Mon, 22 Apr 2024 19:47:50 GMT", `cache-control` = "max-age=0, must-revalidate, no-transform", 
        `strict-transport-security` = "max-age=31536000", `x-content-type-options` = "nosniff", 
        `x-vcap-request-id` = "e73cb647-8e07-4a23-7332-15cba680e26d", 
        `x-xss-protection` = "1; mode=block", `x-frame-options` = "DENY", 
        vary = "Accept-Encoding", `x-cache` = "Error from cloudfront", 
        via = "1.1 0c2947bdc7b8340f8e04a5a58d570236.cloudfront.net (CloudFront)", 
        `x-amz-cf-pop` = "EWR50-C1", `x-amz-cf-id` = "NEZaItTqr5BMq86rTqDR0koHHhwS_y69m5bXf9If2JF5I_WKek_wnw=="), class = c("insensitive", 
    "list")), all_headers = list(list(status = 404L, version = "HTTP/1.1", 
        headers = structure(list(`content-type` = "application/json", 
            `transfer-encoding` = "chunked", connection = "keep-alive", 
            date = "Mon, 22 Apr 2024 19:47:50 GMT", `cache-control` = "max-age=0, must-revalidate, no-transform", 
            `strict-transport-security` = "max-age=31536000", 
            `x-content-type-options` = "nosniff", `x-vcap-request-id` = "e73cb647-8e07-4a23-7332-15cba680e26d", 
            `x-xss-protection` = "1; mode=block", `x-frame-options` = "DENY", 
            vary = "Accept-Encoding", `x-cache` = "Error from cloudfront", 
            via = "1.1 0c2947bdc7b8340f8e04a5a58d570236.cloudfront.net (CloudFront)", 
            `x-amz-cf-pop` = "EWR50-C1", `x-amz-cf-id` = "NEZaItTqr5BMq86rTqDR0koHHhwS_y69m5bXf9If2JF5I_WKek_wnw=="), class = c("insensitive", 
        "list")))), cookies = structure(list(domain = logical(0), 
        flag = logical(0), path = logical(0), secure = logical(0), 
        expiration = structure(numeric(0), class = c("POSIXct", 
        "POSIXt")), name = logical(0), value = logical(0)), row.names = integer(0), class = "data.frame"), 
    content = charToRaw("{\n  \"timestamp\" : \"2024-04-22T19:47:50.344+00:00\",\n  \"status\" : 404,\n  \"error\" : \"Not Found\",\n  \"path\" : \"/exposure/functional-use/search/by-dtxsid/\"\n}"), 
    date = structure(1713815270, class = c("POSIXct", "POSIXt"
    ), tzone = "GMT"), times = c(redirect = 0, namelookup = 4.5e-05, 
    connect = 0, pretransfer = 0.000146, starttransfer = 0.225296, 
    total = 0.225358)), class = "response")
