structure(list(url = "https://api-ccte.epa.gov/bioactivity/search/by-aeid/1", 
    status_code = 404L, headers = structure(list(`content-type` = "application/json", 
        `transfer-encoding` = "chunked", connection = "keep-alive", 
        date = "Fri, 22 Mar 2024 12:58:10 GMT", `cache-control` = "no-cache, must-revalidate", 
        `x-vcap-request-id` = "dc7ceaa1-bef1-46da-7df6-6cbb841e6761", 
        `x-frame-options` = "DENY", `strict-transport-security` = "max-age=31536000", 
        `x-content-type-options` = "nosniff", `x-xss-protection` = "1; mode=block", 
        vary = "Accept-Encoding", `x-cache` = "Error from cloudfront", 
        via = "1.1 9f67823435998c04ac9be5fb7449a3c4.cloudfront.net (CloudFront)", 
        `x-amz-cf-pop` = "ATL59-P8", `x-amz-cf-id` = "eFezN36Z3v2qokorK3zl-k5_3Lpx429nzNCtzgQULSYorFGXOB89-w=="), class = c("insensitive", 
    "list")), all_headers = list(list(status = 404L, version = "HTTP/1.1", 
        headers = structure(list(`content-type` = "application/json", 
            `transfer-encoding` = "chunked", connection = "keep-alive", 
            date = "Fri, 22 Mar 2024 12:58:10 GMT", `cache-control` = "no-cache, must-revalidate", 
            `x-vcap-request-id` = "dc7ceaa1-bef1-46da-7df6-6cbb841e6761", 
            `x-frame-options` = "DENY", `strict-transport-security` = "max-age=31536000", 
            `x-content-type-options` = "nosniff", `x-xss-protection` = "1; mode=block", 
            vary = "Accept-Encoding", `x-cache` = "Error from cloudfront", 
            via = "1.1 9f67823435998c04ac9be5fb7449a3c4.cloudfront.net (CloudFront)", 
            `x-amz-cf-pop` = "ATL59-P8", `x-amz-cf-id` = "eFezN36Z3v2qokorK3zl-k5_3Lpx429nzNCtzgQULSYorFGXOB89-w=="), class = c("insensitive", 
        "list")))), cookies = structure(list(domain = logical(0), 
        flag = logical(0), path = logical(0), secure = logical(0), 
        expiration = structure(numeric(0), class = c("POSIXct", 
        "POSIXt")), name = logical(0), value = logical(0)), row.names = integer(0), class = "data.frame"), 
    content = charToRaw("{\n  \"timestamp\" : \"2024-03-22T12:58:10.626+00:00\",\n  \"status\" : 404,\n  \"error\" : \"Not Found\",\n  \"path\" : \"/bioactivity/search/by-aeid/1\"\n}"), 
    date = structure(1711112290, class = c("POSIXct", "POSIXt"
    ), tzone = "GMT"), times = c(redirect = 0, namelookup = 4e-05, 
    connect = 0, pretransfer = 0.000134, starttransfer = 0.301496, 
    total = 0.301526)), class = "response")
