structure(list(url = "https://api-ccte.epa.gov/exposure/functional-use/probability/search/by-dtxsid/", 
    status_code = 404L, headers = structure(list(`content-type` = "application/json", 
        `transfer-encoding` = "chunked", connection = "keep-alive", 
        date = "Wed, 24 Apr 2024 20:00:54 GMT", `cache-control` = "max-age=0, must-revalidate, no-transform", 
        `strict-transport-security` = "max-age=31536000", `x-content-type-options` = "nosniff", 
        `x-vcap-request-id` = "17ade3d6-ae53-4e61-4ccd-56cc3fed525e", 
        `x-xss-protection` = "1; mode=block", `x-frame-options` = "DENY", 
        vary = "Accept-Encoding", `x-cache` = "Error from cloudfront", 
        via = "1.1 0c2947bdc7b8340f8e04a5a58d570236.cloudfront.net (CloudFront)", 
        `x-amz-cf-pop` = "EWR50-C1", `x-amz-cf-id` = "mTkrsiZj3WRqoqqry_tqUffQ_YKzNJIG222RQpGjlXZnd_5Q4h-6nQ=="), class = c("insensitive", 
    "list")), all_headers = list(list(status = 404L, version = "HTTP/1.1", 
        headers = structure(list(`content-type` = "application/json", 
            `transfer-encoding` = "chunked", connection = "keep-alive", 
            date = "Wed, 24 Apr 2024 20:00:54 GMT", `cache-control` = "max-age=0, must-revalidate, no-transform", 
            `strict-transport-security` = "max-age=31536000", 
            `x-content-type-options` = "nosniff", `x-vcap-request-id` = "17ade3d6-ae53-4e61-4ccd-56cc3fed525e", 
            `x-xss-protection` = "1; mode=block", `x-frame-options` = "DENY", 
            vary = "Accept-Encoding", `x-cache` = "Error from cloudfront", 
            via = "1.1 0c2947bdc7b8340f8e04a5a58d570236.cloudfront.net (CloudFront)", 
            `x-amz-cf-pop` = "EWR50-C1", `x-amz-cf-id` = "mTkrsiZj3WRqoqqry_tqUffQ_YKzNJIG222RQpGjlXZnd_5Q4h-6nQ=="), class = c("insensitive", 
        "list")))), cookies = structure(list(domain = logical(0), 
        flag = logical(0), path = logical(0), secure = logical(0), 
        expiration = structure(numeric(0), class = c("POSIXct", 
        "POSIXt")), name = logical(0), value = logical(0)), row.names = integer(0), class = "data.frame"), 
    content = charToRaw("{\n  \"timestamp\" : \"2024-04-24T20:00:54.407+00:00\",\n  \"status\" : 404,\n  \"error\" : \"Not Found\",\n  \"path\" : \"/exposure/functional-use/probability/search/by-dtxsid/\"\n}"), 
    date = structure(1713988854, class = c("POSIXct", "POSIXt"
    ), tzone = "GMT"), times = c(redirect = 0, namelookup = 9.1e-05, 
    connect = 0, pretransfer = 0.000307, starttransfer = 0.295917, 
    total = 0.296034)), class = "response")
