structure(list(url = "https://api-ccte-stg.epa.gov/exposure/seem/demographic/search/by-dtxsid/", 
    status_code = 404L, headers = structure(list(`content-type` = "application/json", 
        `transfer-encoding` = "chunked", connection = "keep-alive", 
        date = "Tue, 16 Jul 2024 19:56:51 GMT", `cache-control` = "max-age=0, must-revalidate, no-transform", 
        `strict-transport-security` = "max-age=31536000", `x-content-type-options` = "nosniff", 
        `x-vcap-request-id` = "758e7688-3487-47f8-6eb0-0aaeb7eeb7d2", 
        `x-xss-protection` = "1; mode=block", `x-frame-options` = "DENY", 
        vary = "Accept-Encoding", `x-cache` = "Error from cloudfront", 
        via = "1.1 def26d054ec95b961e8352e3cd4fae7e.cloudfront.net (CloudFront)", 
        `x-amz-cf-pop` = "JFK52-P3", `x-amz-cf-id` = "CStIdaSAJdfK1n6MyGBgFictiE1UsJmXq-mvgCL8UpXBxuINkpJC3w=="), class = c("insensitive", 
    "list")), all_headers = list(list(status = 404L, version = "HTTP/1.1", 
        headers = structure(list(`content-type` = "application/json", 
            `transfer-encoding` = "chunked", connection = "keep-alive", 
            date = "Tue, 16 Jul 2024 19:56:51 GMT", `cache-control` = "max-age=0, must-revalidate, no-transform", 
            `strict-transport-security` = "max-age=31536000", 
            `x-content-type-options` = "nosniff", `x-vcap-request-id` = "758e7688-3487-47f8-6eb0-0aaeb7eeb7d2", 
            `x-xss-protection` = "1; mode=block", `x-frame-options` = "DENY", 
            vary = "Accept-Encoding", `x-cache` = "Error from cloudfront", 
            via = "1.1 def26d054ec95b961e8352e3cd4fae7e.cloudfront.net (CloudFront)", 
            `x-amz-cf-pop` = "JFK52-P3", `x-amz-cf-id` = "CStIdaSAJdfK1n6MyGBgFictiE1UsJmXq-mvgCL8UpXBxuINkpJC3w=="), class = c("insensitive", 
        "list")))), cookies = structure(list(domain = logical(0), 
        flag = logical(0), path = logical(0), secure = logical(0), 
        expiration = structure(numeric(0), class = c("POSIXct", 
        "POSIXt")), name = logical(0), value = logical(0)), row.names = integer(0), class = "data.frame"), 
    content = charToRaw("{\n  \"timestamp\" : \"2024-07-16T19:56:51.599+00:00\",\n  \"status\" : 404,\n  \"error\" : \"Not Found\",\n  \"path\" : \"/exposure/seem/demographic/search/by-dtxsid/\"\n}"), 
    date = structure(1721159811, class = c("POSIXct", "POSIXt"
    ), tzone = "GMT"), times = c(redirect = 0, namelookup = 4.2e-05, 
    connect = 0, pretransfer = 0.000159, starttransfer = 0.284398, 
    total = 0.284427)), class = "response")
