structure(list(url = "https://api-ccte.epa.gov/chemical/opsin/to-smiles/Acetamide", 
    status_code = 200L, headers = structure(list(`content-type` = "application/json", 
        `content-length` = "9", connection = "keep-alive", date = "Tue, 21 May 2024 17:14:08 GMT", 
        `cache-control` = "max-age=0, must-revalidate, no-transform", 
        `strict-transport-security` = "max-age=31536000", `x-content-type-options` = "nosniff", 
        `x-vcap-request-id` = "34807c48-fa71-4633-6791-683f7a133d71", 
        `x-xss-protection` = "1; mode=block", `x-frame-options` = "DENY", 
        `x-cache` = "Miss from cloudfront", via = "1.1 d7b509440ac55e6d7b3c4c7ad48b08f2.cloudfront.net (CloudFront)", 
        `x-amz-cf-pop` = "IAH50-C2", `x-amz-cf-id` = "vFWGPmK9GRnGjcjFe9PHuQuYXk_-Yr8HINuC8lhPfdoLIUTQp_Oogw=="), class = c("insensitive", 
    "list")), all_headers = list(list(status = 200L, version = "HTTP/1.1", 
        headers = structure(list(`content-type` = "application/json", 
            `content-length` = "9", connection = "keep-alive", 
            date = "Tue, 21 May 2024 17:14:08 GMT", `cache-control` = "max-age=0, must-revalidate, no-transform", 
            `strict-transport-security` = "max-age=31536000", 
            `x-content-type-options` = "nosniff", `x-vcap-request-id` = "34807c48-fa71-4633-6791-683f7a133d71", 
            `x-xss-protection` = "1; mode=block", `x-frame-options` = "DENY", 
            `x-cache` = "Miss from cloudfront", via = "1.1 d7b509440ac55e6d7b3c4c7ad48b08f2.cloudfront.net (CloudFront)", 
            `x-amz-cf-pop` = "IAH50-C2", `x-amz-cf-id` = "vFWGPmK9GRnGjcjFe9PHuQuYXk_-Yr8HINuC8lhPfdoLIUTQp_Oogw=="), class = c("insensitive", 
        "list")))), cookies = structure(list(domain = logical(0), 
        flag = logical(0), path = logical(0), secure = logical(0), 
        expiration = structure(numeric(0), class = c("POSIXct", 
        "POSIXt")), name = logical(0), value = logical(0)), row.names = integer(0), class = "data.frame"), 
    content = charToRaw("C(C)(=O)N"), date = structure(1716311648, class = c("POSIXct", 
    "POSIXt"), tzone = "GMT"), times = c(redirect = 0, namelookup = 4.4e-05, 
    connect = 0, pretransfer = 0.000187, starttransfer = 0.11196, 
    total = 0.11199)), class = "response")
