structure(list(url = "https://api-ccte.epa.gov/chemical/opsin/to-inchi/Acetamide", 
    status_code = 200L, headers = structure(list(`content-type` = "application/json", 
        `content-length` = "44", connection = "keep-alive", date = "Tue, 21 May 2024 17:14:08 GMT", 
        `cache-control` = "max-age=0, must-revalidate, no-transform", 
        `strict-transport-security` = "max-age=31536000", `x-content-type-options` = "nosniff", 
        `x-vcap-request-id` = "cd750e0a-60a1-424f-404a-5bdf26515b42", 
        `x-xss-protection` = "1; mode=block", `x-frame-options` = "DENY", 
        vary = "Accept-Encoding", `x-cache` = "Miss from cloudfront", 
        via = "1.1 d7b509440ac55e6d7b3c4c7ad48b08f2.cloudfront.net (CloudFront)", 
        `x-amz-cf-pop` = "IAH50-C2", `x-amz-cf-id` = "_HB5FRDD9DrQc3CGJC80SvhmaoDP5Mh4pQoj4yAvXK1rFfU8s7RKww=="), class = c("insensitive", 
    "list")), all_headers = list(list(status = 200L, version = "HTTP/1.1", 
        headers = structure(list(`content-type` = "application/json", 
            `content-length` = "44", connection = "keep-alive", 
            date = "Tue, 21 May 2024 17:14:08 GMT", `cache-control` = "max-age=0, must-revalidate, no-transform", 
            `strict-transport-security` = "max-age=31536000", 
            `x-content-type-options` = "nosniff", `x-vcap-request-id` = "cd750e0a-60a1-424f-404a-5bdf26515b42", 
            `x-xss-protection` = "1; mode=block", `x-frame-options` = "DENY", 
            vary = "Accept-Encoding", `x-cache` = "Miss from cloudfront", 
            via = "1.1 d7b509440ac55e6d7b3c4c7ad48b08f2.cloudfront.net (CloudFront)", 
            `x-amz-cf-pop` = "IAH50-C2", `x-amz-cf-id` = "_HB5FRDD9DrQc3CGJC80SvhmaoDP5Mh4pQoj4yAvXK1rFfU8s7RKww=="), class = c("insensitive", 
        "list")))), cookies = structure(list(domain = logical(0), 
        flag = logical(0), path = logical(0), secure = logical(0), 
        expiration = structure(numeric(0), class = c("POSIXct", 
        "POSIXt")), name = logical(0), value = logical(0)), row.names = integer(0), class = "data.frame"), 
    content = charToRaw("InChI=1/C2H5NO/c1-2(3)4/h1H3,(H2,3,4)/f/h3H2"), 
    date = structure(1716311648, class = c("POSIXct", "POSIXt"
    ), tzone = "GMT"), times = c(redirect = 0, namelookup = 4.8e-05, 
    connect = 0, pretransfer = 0.000175, starttransfer = 0.112727, 
    total = 0.112757)), class = "response")
