structure(list(url = "https://api-ccte-stg.epa.gov/exposure/httk/search/by-dtxsid/", 
    status_code = 404L, headers = structure(list(`content-type` = "application/json", 
        `transfer-encoding` = "chunked", connection = "keep-alive", 
        date = "Tue, 16 Jul 2024 19:56:49 GMT", `cache-control` = "max-age=0, must-revalidate, no-transform", 
        `strict-transport-security` = "max-age=31536000", `x-content-type-options` = "nosniff", 
        `x-vcap-request-id` = "d835aa3a-6735-4f0d-52d5-796a758fb653", 
        `x-xss-protection` = "1; mode=block", `x-frame-options` = "DENY", 
        vary = "Accept-Encoding", `x-cache` = "Error from cloudfront", 
        via = "1.1 def26d054ec95b961e8352e3cd4fae7e.cloudfront.net (CloudFront)", 
        `x-amz-cf-pop` = "JFK52-P3", `x-amz-cf-id` = "MNtHugOuY0OLI3DrpS_xNc7IxRNS7UaQU_y41qjEkZpB3-kXrqz8Ag=="), class = c("insensitive", 
    "list")), all_headers = list(list(status = 404L, version = "HTTP/1.1", 
        headers = structure(list(`content-type` = "application/json", 
            `transfer-encoding` = "chunked", connection = "keep-alive", 
            date = "Tue, 16 Jul 2024 19:56:49 GMT", `cache-control` = "max-age=0, must-revalidate, no-transform", 
            `strict-transport-security` = "max-age=31536000", 
            `x-content-type-options` = "nosniff", `x-vcap-request-id` = "d835aa3a-6735-4f0d-52d5-796a758fb653", 
            `x-xss-protection` = "1; mode=block", `x-frame-options` = "DENY", 
            vary = "Accept-Encoding", `x-cache` = "Error from cloudfront", 
            via = "1.1 def26d054ec95b961e8352e3cd4fae7e.cloudfront.net (CloudFront)", 
            `x-amz-cf-pop` = "JFK52-P3", `x-amz-cf-id` = "MNtHugOuY0OLI3DrpS_xNc7IxRNS7UaQU_y41qjEkZpB3-kXrqz8Ag=="), class = c("insensitive", 
        "list")))), cookies = structure(list(domain = logical(0), 
        flag = logical(0), path = logical(0), secure = logical(0), 
        expiration = structure(numeric(0), class = c("POSIXct", 
        "POSIXt")), name = logical(0), value = logical(0)), row.names = integer(0), class = "data.frame"), 
    content = charToRaw("{\n  \"timestamp\" : \"2024-07-16T19:56:49.579+00:00\",\n  \"status\" : 404,\n  \"error\" : \"Not Found\",\n  \"path\" : \"/exposure/httk/search/by-dtxsid/\"\n}"), 
    date = structure(1721159809, class = c("POSIXct", "POSIXt"
    ), tzone = "GMT"), times = c(redirect = 0, namelookup = 3.7e-05, 
    connect = 0, pretransfer = 0.000124, starttransfer = 0.298112, 
    total = 0.29814)), class = "response")
