structure(list(url = "https://api-ccte.epa.gov/chemical/msready/search/by-dtxcid/DTXCID30182", 
    status_code = 401L, headers = structure(list(`content-type` = "application/json;charset=ISO-8859-1", 
        `content-length` = "164", connection = "keep-alive", 
        date = "Mon, 16 Sep 2024 17:11:23 GMT", `strict-transport-security` = "max-age=31536000", 
        `x-content-type-options` = "nosniff", `x-vcap-request-id` = "eebc34fd-dc7e-48d8-682f-c74f58b19e59", 
        `x-xss-protection` = "1; mode=block", `x-frame-options` = "DENY", 
        `x-cache` = "Error from cloudfront", via = "1.1 8fc9659fc06389e49927f68638e9bc94.cloudfront.net (CloudFront)", 
        `x-amz-cf-pop` = "IAD89-C1", `x-amz-cf-id` = "8yK9KibiFKz7L-f7X3JJ1dvkmauorEfbJ9VlYm2lOkzmGzWR02VOYg=="), class = c("insensitive", 
    "list")), all_headers = list(list(status = 401L, version = "HTTP/1.1", 
        headers = structure(list(`content-type` = "application/json;charset=ISO-8859-1", 
            `content-length` = "164", connection = "keep-alive", 
            date = "Mon, 16 Sep 2024 17:11:23 GMT", `strict-transport-security` = "max-age=31536000", 
            `x-content-type-options` = "nosniff", `x-vcap-request-id` = "eebc34fd-dc7e-48d8-682f-c74f58b19e59", 
            `x-xss-protection` = "1; mode=block", `x-frame-options` = "DENY", 
            `x-cache` = "Error from cloudfront", via = "1.1 8fc9659fc06389e49927f68638e9bc94.cloudfront.net (CloudFront)", 
            `x-amz-cf-pop` = "IAD89-C1", `x-amz-cf-id` = "8yK9KibiFKz7L-f7X3JJ1dvkmauorEfbJ9VlYm2lOkzmGzWR02VOYg=="), class = c("insensitive", 
        "list")))), cookies = structure(list(domain = logical(0), 
        flag = logical(0), path = logical(0), secure = logical(0), 
        expiration = structure(numeric(0), class = c("POSIXct", 
        "POSIXt")), name = logical(0), value = logical(0)), row.names = integer(0), class = "data.frame"), 
    content = charToRaw("{\"title\":\"API Header Not Found\",\"detail\":\"Every API call should pass assigned API key through custom http header or query parameter. Request is missing x-api-key.\"}"), 
    date = structure(1726506683, class = c("POSIXct", "POSIXt"
    ), tzone = "GMT"), times = c(redirect = 0, namelookup = 5.2e-05, 
    connect = 0, pretransfer = 0.000125, starttransfer = 0.133303, 
    total = 0.133367)), class = "response")
